
//! Autogenerated weights for validatorset
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2023-03-06, STEPS: `50`, REPEAT: 20, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! HOSTNAME: `R1-HP-ProBook-630-G8`, CPU: `11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
// ./target/release/tfchain
// benchmark
// pallet
// --chain=dev
// --pallet=validatorset
// --extrinsic=*
// --steps=50
// --repeat=20
// --execution=wasm
// --heap-pages=4096
// --output
// pallets/substrate-validator-set/src/weights.rs
// --template
// ./.maintain/frame-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use sp_std::marker::PhantomData;

/// Weight functions needed for validatorset.
pub trait WeightInfo {
	fn add_validator() -> Weight;
	fn remove_validator() -> Weight;
	fn add_validator_again() -> Weight;
}

/// Weights for validatorset using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	// Storage: ValidatorSet Validators (r:1 w:1)
	// Storage: ValidatorSet ApprovedValidators (r:1 w:1)
	fn add_validator() -> Weight {
		// Minimum execution time: 30_657 nanoseconds.
		Weight::from_ref_time(32_190_000)
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	// Storage: ValidatorSet Validators (r:1 w:1)
	// Storage: ValidatorSet ApprovedValidators (r:1 w:0)
	fn remove_validator() -> Weight {
		// Minimum execution time: 26_349 nanoseconds.
		Weight::from_ref_time(27_135_000)
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	// Storage: ValidatorSet ApprovedValidators (r:1 w:0)
	// Storage: ValidatorSet Validators (r:1 w:1)
	fn add_validator_again() -> Weight {
		// Minimum execution time: 32_656 nanoseconds.
		Weight::from_ref_time(36_279_000)
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}
}

// For backwards compatibility and tests
impl WeightInfo for () {
	// Storage: ValidatorSet Validators (r:1 w:1)
	// Storage: ValidatorSet ApprovedValidators (r:1 w:1)
	fn add_validator() -> Weight {
		// Minimum execution time: 30_657 nanoseconds.
		Weight::from_ref_time(32_190_000)
			.saturating_add(RocksDbWeight::get().reads(2))
			.saturating_add(RocksDbWeight::get().writes(2))
	}
	// Storage: ValidatorSet Validators (r:1 w:1)
	// Storage: ValidatorSet ApprovedValidators (r:1 w:0)
	fn remove_validator() -> Weight {
		// Minimum execution time: 26_349 nanoseconds.
		Weight::from_ref_time(27_135_000)
			.saturating_add(RocksDbWeight::get().reads(2))
			.saturating_add(RocksDbWeight::get().writes(1))
	}
	// Storage: ValidatorSet ApprovedValidators (r:1 w:0)
	// Storage: ValidatorSet Validators (r:1 w:1)
	fn add_validator_again() -> Weight {
		// Minimum execution time: 32_656 nanoseconds.
		Weight::from_ref_time(36_279_000)
			.saturating_add(RocksDbWeight::get().reads(2))
			.saturating_add(RocksDbWeight::get().writes(1))
	}
}