name: Lint
on:
  pull_request:
    paths-ignore:
      - "readme.md"
  push:
    paths-ignore:
      - "readme.md"

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.19"
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3.2.0
        with:
          submodules: "true"

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          args: --timeout 3m --verbose

      - name: gofmt
        uses: Jerome1337/gofmt-action@v1.0.5
        with:
          gofmt-flags: "-l -d"