name: test-substrate-client

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: install go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: run docker image
        run: docker run -d -p 9944:9944 threefolddev/tfchain:2.3.0-rc2 --dev --ws-external

      - name: wait for node initialization
        run: sleep 3

      - name: run test
        run: go test -v ./...
