
//! Autogenerated weights for pallet_smart_contract
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2023-06-14, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `R1-HP-ProBook-630-G8`, CPU: `11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
// ./target/release/tfchain
// benchmark
// pallet
// --chain=dev
// --pallet=pallet_smart_contract
// --extrinsic=*
// --steps=50
// --repeat=20
// --execution=wasm
// --heap-pages=409
// --output
// ./pallets/pallet-smart-contract/src/weights.rs
// --template
// ./.maintain/frame-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for pallet_smart_contract.
pub trait WeightInfo {
	fn create_node_contract() -> Weight;
	fn update_node_contract() -> Weight;
	fn cancel_contract() -> Weight;
	fn create_name_contract() -> Weight;
	fn cancel_name_contract() -> Weight;
	fn add_nru_reports() -> Weight;
	fn report_contract_resources() -> Weight;
	fn create_rent_contract() -> Weight;
	fn cancel_rent_contract() -> Weight;
	fn create_solution_provider() -> Weight;
	fn approve_solution_provider() -> Weight;
	fn bill_contract_for_block() -> Weight;
	fn service_contract_create() -> Weight;
	fn service_contract_set_metadata() -> Weight;
	fn service_contract_set_fees() -> Weight;
	fn service_contract_approve() -> Weight;
	fn service_contract_reject() -> Weight;
	fn service_contract_cancel() -> Weight;
	fn service_contract_bill() -> Weight;
	fn change_billing_frequency() -> Weight;
	fn attach_solution_provider_id() -> Weight;
	fn set_dedicated_node_extra_fee() -> Weight;
}

/// Weights for pallet_smart_contract using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: TfgridModule TwinIdByAccountID (r:1 w:0)
	/// Proof Skipped: TfgridModule TwinIdByAccountID (max_values: None, max_size: None, mode: Measured)
	/// Storage: TfgridModule Nodes (r:1 w:0)
	/// Proof Skipped: TfgridModule Nodes (max_values: None, max_size: None, mode: Measured)
	/// Storage: TfgridModule NodePower (r:1 w:0)
	/// Proof Skipped: TfgridModule NodePower (max_values: None, max_size: None, mode: Measured)
	/// Storage: TfgridModule Farms (r:1 w:1)
	/// Proof Skipped: TfgridModule Farms (max_values: None, max_size: None, mode: Measured)
	/// Storage: SmartContractModule ActiveRentContractForNode (r:1 w:0)
	/// Proof Skipped: SmartContractModule ActiveRentContractForNode (max_values: None, max_size: None, mode: Measured)
	/// Storage: SmartContractModule DedicatedNodesExtraFee (r:1 w:0)
	/// Proof Skipped: SmartContractModule DedicatedNodesExtraFee (max_values: None, max_size: None, mode: Measured)
	/// Storage: SmartContractModule ContractIDByNodeIDAndHash (r:1 w:1)
	/// Proof Skipped: SmartContractModule ContractIDByNodeIDAndHash (max_values: None, max_size: None, mode: Measured)
	/// Storage: SmartContractModule ContractID (r:1 w:1)
	/// Proof Skipped: SmartContractModule ContractID (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: SmartContractModule BillingFrequency (r:1 w:0)
	/// Proof Skipped: SmartContractModule BillingFrequency (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: SmartContractModule ContractsToBillAt (r:1 w:1)
	/// Proof Skipped: SmartContractModule ContractsToBillAt (max_values: None, max_size: None, mode: Measured)
	/// Storage: Timestamp Now (r:1 w:0)
	/// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: SmartContractModule ActiveNodeContracts (r:1 w:1)
	/// Proof Skipped: SmartContractModule ActiveNodeContracts (max_values: None, max_size: None, mode: Measured)
	/// Storage: SmartContractModule Contracts (r:0 w:1)
	/// Proof Skipped: SmartContractModule Contracts (max_values: None, max_size: None, mode: Measured)
	/// Storage: SmartContractModule ContractBillingInformationByID (r:0 w:1)
	/// Proof Skipped: SmartContractModule ContractBillingInformationByID (max_values: None, max_size: None, mode: Measured)
	/// Storage: SmartContractModule ContractLock (r:0 w:1)
	/// Proof Skipped: SmartContractModule ContractLock (max_values: None, max_size: None, mode: Measured)
	fn create_node_contract() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `868`
		//  Estimated: `4333`
		// Minimum execution time: 119_629_000 picoseconds.
		Weight::from_parts(124_124_000, 4333)
			.saturating_add(T::DbWeight::get().reads(12_u64))
			.saturating_add(T::DbWeight::get().writes(8_u64))
	}
	/// Storage: SmartContractModule Contracts (r:1 w:1)
	/// Proof Skipped: SmartContractModule Contracts (max_values: None, max_size: None, mode: Measured)
	/// Storage: TfgridModule Twins (r:1 w:0)
	/// Proof Skipped: TfgridModule Twins (max_values: None, max_size: None, mode: Measured)
	/// Storage: SmartContractModule ActiveNodeContracts (r:1 w:1)
	/// Proof Skipped: SmartContractModule ActiveNodeContracts (max_values: None, max_size: None, mode: Measured)
	/// Storage: SmartContractModule ContractIDByNodeIDAndHash (r:0 w:2)
	/// Proof Skipped: SmartContractModule ContractIDByNodeIDAndHash (max_values: None, max_size: None, mode: Measured)
	fn update_node_contract() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `892`
		//  Estimated: `4357`
		// Minimum execution time: 64_128_000 picoseconds.
		Weight::from_parts(67_016_000, 4357)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(4_u64))
	}
	/// Storage: SmartContractModule Contracts (r:1 w:1)
	/// Proof Skipped: SmartContractModule Contracts (max_values: None, max_size: None, mode: Measured)
	/// Storage: TfgridModule Twins (r:1 w:0)
	/// Proof Skipped: TfgridModule Twins (max_values: None, max_size: None, mode: Measured)
	/// Storage: SmartContractModule ActiveNodeContracts (r:1 w:1)
	/// Proof Skipped: SmartContractModule ActiveNodeContracts (max_values: None, max_size: None, mode: Measured)
	/// Storage: TfgridModule TwinBoundedAccountID (r:1 w:0)
	/// Proof Skipped: TfgridModule TwinBoundedAccountID (max_values: None, max_size: None, mode: Measured)
	/// Storage: Timestamp Now (r:1 w:0)
	/// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: SmartContractModule ContractLock (r:1 w:1)
	/// Proof Skipped: SmartContractModule ContractLock (max_values: None, max_size: None, mode: Measured)
	/// Storage: TfgridModule PricingPolicies (r:1 w:0)
	/// Proof Skipped: TfgridModule PricingPolicies (max_values: None, max_size: None, mode: Measured)
	/// Storage: SmartContractModule BillingFrequency (r:1 w:0)
	/// Proof Skipped: SmartContractModule BillingFrequency (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: SmartContractModule ContractsToBillAt (r:1 w:1)
	/// Proof Skipped: SmartContractModule ContractsToBillAt (max_values: None, max_size: None, mode: Measured)
	/// Storage: SmartContractModule ContractBillingInformationByID (r:0 w:1)
	/// Proof Skipped: SmartContractModule ContractBillingInformationByID (max_values: None, max_size: None, mode: Measured)
	/// Storage: SmartContractModule NodeContractResources (r:0 w:1)
	/// Proof Skipped: SmartContractModule NodeContractResources (max_values: None, max_size: None, mode: Measured)
	/// Storage: SmartContractModule ContractIDByNodeIDAndHash (r:0 w:1)
	/// Proof Skipped: SmartContractModule ContractIDByNodeIDAndHash (max_values: None, max_size: None, mode: Measured)
	fn cancel_contract() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1203`
		//  Estimated: `4668`
		// Minimum execution time: 134_164_000 picoseconds.
		Weight::from_parts(138_183_000, 4668)
			.saturating_add(T::DbWeight::get().reads(9_u64))
			.saturating_add(T::DbWeight::get().writes(7_u64))
	}
	/// Storage: TfgridModule TwinIdByAccountID (r:1 w:0)
	/// Proof Skipped: TfgridModule TwinIdByAccountID (max_values: None, max_size: None, mode: Measured)
	/// Storage: SmartContractModule ContractIDByNameRegistration (r:1 w:1)
	/// Proof Skipped: SmartContractModule ContractIDByNameRegistration (max_values: None, max_size: None, mode: Measured)
	/// Storage: SmartContractModule ContractID (r:1 w:1)
	/// Proof Skipped: SmartContractModule ContractID (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: SmartContractModule BillingFrequency (r:1 w:0)
	/// Proof Skipped: SmartContractModule BillingFrequency (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: SmartContractModule ContractsToBillAt (r:1 w:1)
	/// Proof Skipped: SmartContractModule ContractsToBillAt (max_values: None, max_size: None, mode: Measured)
	/// Storage: Timestamp Now (r:1 w:0)
	/// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: SmartContractModule Contracts (r:0 w:1)
	/// Proof Skipped: SmartContractModule Contracts (max_values: None, max_size: None, mode: Measured)
	/// Storage: SmartContractModule ContractLock (r:0 w:1)
	/// Proof Skipped: SmartContractModule ContractLock (max_values: None, max_size: None, mode: Measured)
	fn create_name_contract() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `340`
		//  Estimated: `3805`
		// Minimum execution time: 54_724_000 picoseconds.
		Weight::from_parts(57_496_000, 3805)
			.saturating_add(T::DbWeight::get().reads(6_u64))
			.saturating_add(T::DbWeight::get().writes(5_u64))
	}
	/// Storage: SmartContractModule Contracts (r:1 w:1)
	/// Proof Skipped: SmartContractModule Contracts (max_values: None, max_size: None, mode: Measured)
	/// Storage: TfgridModule Twins (r:1 w:0)
	/// Proof Skipped: TfgridModule Twins (max_values: None, max_size: None, mode: Measured)
	/// Storage: TfgridModule TwinBoundedAccountID (r:1 w:0)
	/// Proof Skipped: TfgridModule TwinBoundedAccountID (max_values: None, max_size: None, mode: Measured)
	/// Storage: Timestamp Now (r:1 w:0)
	/// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: SmartContractModule ContractLock (r:1 w:1)
	/// Proof Skipped: SmartContractModule ContractLock (max_values: None, max_size: None, mode: Measured)
	/// Storage: TfgridModule PricingPolicies (r:1 w:0)
	/// Proof Skipped: TfgridModule PricingPolicies (max_values: None, max_size: None, mode: Measured)
	/// Storage: SmartContractModule BillingFrequency (r:1 w:0)
	/// Proof Skipped: SmartContractModule BillingFrequency (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: SmartContractModule ContractsToBillAt (r:1 w:1)
	/// Proof Skipped: SmartContractModule ContractsToBillAt (max_values: None, max_size: None, mode: Measured)
	/// Storage: SmartContractModule ContractIDByNameRegistration (r:0 w:1)
	/// Proof Skipped: SmartContractModule ContractIDByNameRegistration (max_values: None, max_size: None, mode: Measured)
	fn cancel_name_contract() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `919`
		//  Estimated: `4384`
		// Minimum execution time: 101_753_000 picoseconds.
		Weight::from_parts(105_128_000, 4384)
			.saturating_add(T::DbWeight::get().reads(8_u64))
			.saturating_add(T::DbWeight::get().writes(4_u64))
	}
	/// Storage: TfgridModule TwinIdByAccountID (r:1 w:0)
	/// Proof Skipped: TfgridModule TwinIdByAccountID (max_values: None, max_size: None, mode: Measured)
	/// Storage: TfgridModule NodeIdByTwinID (r:1 w:0)
	/// Proof Skipped: TfgridModule NodeIdByTwinID (max_values: None, max_size: None, mode: Measured)
	/// Storage: TfgridModule Nodes (r:1 w:0)
	/// Proof Skipped: TfgridModule Nodes (max_values: None, max_size: None, mode: Measured)
	/// Storage: TfgridModule Farms (r:1 w:0)
	/// Proof Skipped: TfgridModule Farms (max_values: None, max_size: None, mode: Measured)
	/// Storage: TfgridModule PricingPolicies (r:1 w:0)
	/// Proof Skipped: TfgridModule PricingPolicies (max_values: None, max_size: None, mode: Measured)
	/// Storage: SmartContractModule Contracts (r:1 w:0)
	/// Proof Skipped: SmartContractModule Contracts (max_values: None, max_size: None, mode: Measured)
	/// Storage: SmartContractModule ContractBillingInformationByID (r:1 w:1)
	/// Proof Skipped: SmartContractModule ContractBillingInformationByID (max_values: None, max_size: None, mode: Measured)
	fn add_nru_reports() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1292`
		//  Estimated: `4757`
		// Minimum execution time: 77_126_000 picoseconds.
		Weight::from_parts(79_222_000, 4757)
			.saturating_add(T::DbWeight::get().reads(7_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: TfgridModule TwinIdByAccountID (r:1 w:0)
	/// Proof Skipped: TfgridModule TwinIdByAccountID (max_values: None, max_size: None, mode: Measured)
	/// Storage: TfgridModule NodeIdByTwinID (r:1 w:0)
	/// Proof Skipped: TfgridModule NodeIdByTwinID (max_values: None, max_size: None, mode: Measured)
	/// Storage: SmartContractModule Contracts (r:1 w:0)
	/// Proof Skipped: SmartContractModule Contracts (max_values: None, max_size: None, mode: Measured)
	/// Storage: SmartContractModule NodeContractResources (r:0 w:1)
	/// Proof Skipped: SmartContractModule NodeContractResources (max_values: None, max_size: None, mode: Measured)
	fn report_contract_resources() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `771`
		//  Estimated: `4236`
		// Minimum execution time: 47_460_000 picoseconds.
		Weight::from_parts(48_914_000, 4236)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: SmartContractModule ActiveRentContractForNode (r:1 w:1)
	/// Proof Skipped: SmartContractModule ActiveRentContractForNode (max_values: None, max_size: None, mode: Measured)
	/// Storage: TfgridModule Nodes (r:1 w:0)
	/// Proof Skipped: TfgridModule Nodes (max_values: None, max_size: None, mode: Measured)
	/// Storage: TfgridModule Farms (r:1 w:0)
	/// Proof Skipped: TfgridModule Farms (max_values: None, max_size: None, mode: Measured)
	/// Storage: TfgridModule NodePower (r:1 w:0)
	/// Proof Skipped: TfgridModule NodePower (max_values: None, max_size: None, mode: Measured)
	/// Storage: SmartContractModule ActiveNodeContracts (r:1 w:0)
	/// Proof Skipped: SmartContractModule ActiveNodeContracts (max_values: None, max_size: None, mode: Measured)
	/// Storage: TfgridModule TwinIdByAccountID (r:1 w:0)
	/// Proof Skipped: TfgridModule TwinIdByAccountID (max_values: None, max_size: None, mode: Measured)
	/// Storage: SmartContractModule ContractID (r:1 w:1)
	/// Proof Skipped: SmartContractModule ContractID (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: SmartContractModule BillingFrequency (r:1 w:0)
	/// Proof Skipped: SmartContractModule BillingFrequency (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: SmartContractModule ContractsToBillAt (r:1 w:1)
	/// Proof Skipped: SmartContractModule ContractsToBillAt (max_values: None, max_size: None, mode: Measured)
	/// Storage: Timestamp Now (r:1 w:0)
	/// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: SmartContractModule Contracts (r:0 w:1)
	/// Proof Skipped: SmartContractModule Contracts (max_values: None, max_size: None, mode: Measured)
	/// Storage: SmartContractModule ContractLock (r:0 w:1)
	/// Proof Skipped: SmartContractModule ContractLock (max_values: None, max_size: None, mode: Measured)
	fn create_rent_contract() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `868`
		//  Estimated: `4333`
		// Minimum execution time: 78_140_000 picoseconds.
		Weight::from_parts(81_100_000, 4333)
			.saturating_add(T::DbWeight::get().reads(10_u64))
			.saturating_add(T::DbWeight::get().writes(5_u64))
	}
	/// Storage: SmartContractModule Contracts (r:1 w:1)
	/// Proof Skipped: SmartContractModule Contracts (max_values: None, max_size: None, mode: Measured)
	/// Storage: TfgridModule Twins (r:1 w:0)
	/// Proof Skipped: TfgridModule Twins (max_values: None, max_size: None, mode: Measured)
	/// Storage: SmartContractModule ActiveNodeContracts (r:1 w:0)
	/// Proof Skipped: SmartContractModule ActiveNodeContracts (max_values: None, max_size: None, mode: Measured)
	/// Storage: TfgridModule TwinBoundedAccountID (r:1 w:0)
	/// Proof Skipped: TfgridModule TwinBoundedAccountID (max_values: None, max_size: None, mode: Measured)
	/// Storage: Timestamp Now (r:1 w:0)
	/// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: SmartContractModule ContractLock (r:1 w:1)
	/// Proof Skipped: SmartContractModule ContractLock (max_values: None, max_size: None, mode: Measured)
	/// Storage: TfgridModule PricingPolicies (r:1 w:0)
	/// Proof Skipped: TfgridModule PricingPolicies (max_values: None, max_size: None, mode: Measured)
	/// Storage: SmartContractModule DedicatedNodesExtraFee (r:1 w:0)
	/// Proof Skipped: SmartContractModule DedicatedNodesExtraFee (max_values: None, max_size: None, mode: Measured)
	/// Storage: SmartContractModule BillingFrequency (r:1 w:0)
	/// Proof Skipped: SmartContractModule BillingFrequency (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: SmartContractModule ContractsToBillAt (r:1 w:1)
	/// Proof Skipped: SmartContractModule ContractsToBillAt (max_values: None, max_size: None, mode: Measured)
	/// Storage: SmartContractModule ActiveRentContractForNode (r:0 w:1)
	/// Proof Skipped: SmartContractModule ActiveRentContractForNode (max_values: None, max_size: None, mode: Measured)
	fn cancel_rent_contract() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1071`
		//  Estimated: `4536`
		// Minimum execution time: 114_334_000 picoseconds.
		Weight::from_parts(118_126_000, 4536)
			.saturating_add(T::DbWeight::get().reads(10_u64))
			.saturating_add(T::DbWeight::get().writes(4_u64))
	}
	/// Storage: SmartContractModule SolutionProviderID (r:1 w:1)
	/// Proof Skipped: SmartContractModule SolutionProviderID (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: SmartContractModule SolutionProviders (r:0 w:1)
	/// Proof Skipped: SmartContractModule SolutionProviders (max_values: None, max_size: None, mode: Measured)
	fn create_solution_provider() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `37`
		//  Estimated: `1522`
		// Minimum execution time: 24_361_000 picoseconds.
		Weight::from_parts(25_532_000, 1522)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: SmartContractModule SolutionProviders (r:1 w:1)
	/// Proof Skipped: SmartContractModule SolutionProviders (max_values: None, max_size: None, mode: Measured)
	fn approve_solution_provider() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `215`
		//  Estimated: `3680`
		// Minimum execution time: 28_651_000 picoseconds.
		Weight::from_parts(29_486_000, 3680)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: SmartContractModule Contracts (r:1 w:0)
	/// Proof Skipped: SmartContractModule Contracts (max_values: None, max_size: None, mode: Measured)
	/// Storage: TfgridModule Twins (r:1 w:0)
	/// Proof Skipped: TfgridModule Twins (max_values: None, max_size: None, mode: Measured)
	/// Storage: System Account (r:1 w:0)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// Storage: TfgridModule TwinBoundedAccountID (r:1 w:0)
	/// Proof Skipped: TfgridModule TwinBoundedAccountID (max_values: None, max_size: None, mode: Measured)
	/// Storage: Timestamp Now (r:1 w:0)
	/// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: SmartContractModule ContractLock (r:1 w:0)
	/// Proof Skipped: SmartContractModule ContractLock (max_values: None, max_size: None, mode: Measured)
	/// Storage: TfgridModule PricingPolicies (r:1 w:0)
	/// Proof Skipped: TfgridModule PricingPolicies (max_values: None, max_size: None, mode: Measured)
	fn bill_contract_for_block() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1216`
		//  Estimated: `4681`
		// Minimum execution time: 56_839_000 picoseconds.
		Weight::from_parts(58_569_000, 4681)
			.saturating_add(T::DbWeight::get().reads(7_u64))
	}
	/// Storage: TfgridModule TwinIdByAccountID (r:2 w:0)
	/// Proof Skipped: TfgridModule TwinIdByAccountID (max_values: None, max_size: None, mode: Measured)
	/// Storage: SmartContractModule ServiceContractID (r:1 w:1)
	/// Proof Skipped: SmartContractModule ServiceContractID (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: SmartContractModule ServiceContracts (r:0 w:1)
	/// Proof Skipped: SmartContractModule ServiceContracts (max_values: None, max_size: None, mode: Measured)
	fn service_contract_create() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `395`
		//  Estimated: `6335`
		// Minimum execution time: 40_172_000 picoseconds.
		Weight::from_parts(41_719_000, 6335)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: TfgridModule TwinIdByAccountID (r:1 w:0)
	/// Proof Skipped: TfgridModule TwinIdByAccountID (max_values: None, max_size: None, mode: Measured)
	/// Storage: SmartContractModule ServiceContracts (r:1 w:1)
	/// Proof Skipped: SmartContractModule ServiceContracts (max_values: None, max_size: None, mode: Measured)
	fn service_contract_set_metadata() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `489`
		//  Estimated: `3954`
		// Minimum execution time: 35_442_000 picoseconds.
		Weight::from_parts(36_518_000, 3954)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: TfgridModule TwinIdByAccountID (r:1 w:0)
	/// Proof Skipped: TfgridModule TwinIdByAccountID (max_values: None, max_size: None, mode: Measured)
	/// Storage: SmartContractModule ServiceContracts (r:1 w:1)
	/// Proof Skipped: SmartContractModule ServiceContracts (max_values: None, max_size: None, mode: Measured)
	fn service_contract_set_fees() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `489`
		//  Estimated: `3954`
		// Minimum execution time: 34_663_000 picoseconds.
		Weight::from_parts(35_371_000, 3954)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: TfgridModule TwinIdByAccountID (r:1 w:0)
	/// Proof Skipped: TfgridModule TwinIdByAccountID (max_values: None, max_size: None, mode: Measured)
	/// Storage: SmartContractModule ServiceContracts (r:1 w:1)
	/// Proof Skipped: SmartContractModule ServiceContracts (max_values: None, max_size: None, mode: Measured)
	fn service_contract_approve() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `502`
		//  Estimated: `3967`
		// Minimum execution time: 34_967_000 picoseconds.
		Weight::from_parts(36_503_000, 3967)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: TfgridModule TwinIdByAccountID (r:1 w:0)
	/// Proof Skipped: TfgridModule TwinIdByAccountID (max_values: None, max_size: None, mode: Measured)
	/// Storage: SmartContractModule ServiceContracts (r:1 w:1)
	/// Proof Skipped: SmartContractModule ServiceContracts (max_values: None, max_size: None, mode: Measured)
	fn service_contract_reject() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `502`
		//  Estimated: `3967`
		// Minimum execution time: 36_210_000 picoseconds.
		Weight::from_parts(37_826_000, 3967)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: TfgridModule TwinIdByAccountID (r:1 w:0)
	/// Proof Skipped: TfgridModule TwinIdByAccountID (max_values: None, max_size: None, mode: Measured)
	/// Storage: SmartContractModule ServiceContracts (r:1 w:1)
	/// Proof Skipped: SmartContractModule ServiceContracts (max_values: None, max_size: None, mode: Measured)
	fn service_contract_cancel() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `502`
		//  Estimated: `3967`
		// Minimum execution time: 33_426_000 picoseconds.
		Weight::from_parts(34_600_000, 3967)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: TfgridModule TwinIdByAccountID (r:1 w:0)
	/// Proof Skipped: TfgridModule TwinIdByAccountID (max_values: None, max_size: None, mode: Measured)
	/// Storage: SmartContractModule ServiceContracts (r:1 w:1)
	/// Proof Skipped: SmartContractModule ServiceContracts (max_values: None, max_size: None, mode: Measured)
	/// Storage: Timestamp Now (r:1 w:0)
	/// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: TfgridModule Twins (r:2 w:0)
	/// Proof Skipped: TfgridModule Twins (max_values: None, max_size: None, mode: Measured)
	/// Storage: System Account (r:1 w:0)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	fn service_contract_bill() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `841`
		//  Estimated: `6781`
		// Minimum execution time: 61_064_000 picoseconds.
		Weight::from_parts(64_267_000, 6781)
			.saturating_add(T::DbWeight::get().reads(6_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: SmartContractModule BillingFrequency (r:1 w:1)
	/// Proof Skipped: SmartContractModule BillingFrequency (max_values: Some(1), max_size: None, mode: Measured)
	fn change_billing_frequency() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `37`
		//  Estimated: `1522`
		// Minimum execution time: 17_066_000 picoseconds.
		Weight::from_parts(17_649_000, 1522)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: SmartContractModule SolutionProviders (r:1 w:0)
	/// Proof Skipped: SmartContractModule SolutionProviders (max_values: None, max_size: None, mode: Measured)
	/// Storage: SmartContractModule Contracts (r:1 w:1)
	/// Proof Skipped: SmartContractModule Contracts (max_values: None, max_size: None, mode: Measured)
	/// Storage: TfgridModule TwinIdByAccountID (r:1 w:0)
	/// Proof Skipped: TfgridModule TwinIdByAccountID (max_values: None, max_size: None, mode: Measured)
	fn attach_solution_provider_id() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `971`
		//  Estimated: `4436`
		// Minimum execution time: 44_207_000 picoseconds.
		Weight::from_parts(46_180_000, 4436)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: TfgridModule TwinIdByAccountID (r:1 w:0)
	/// Proof Skipped: TfgridModule TwinIdByAccountID (max_values: None, max_size: None, mode: Measured)
	/// Storage: TfgridModule Nodes (r:1 w:0)
	/// Proof Skipped: TfgridModule Nodes (max_values: None, max_size: None, mode: Measured)
	/// Storage: TfgridModule Farms (r:1 w:0)
	/// Proof Skipped: TfgridModule Farms (max_values: None, max_size: None, mode: Measured)
	/// Storage: SmartContractModule ActiveRentContractForNode (r:1 w:0)
	/// Proof Skipped: SmartContractModule ActiveRentContractForNode (max_values: None, max_size: None, mode: Measured)
	/// Storage: SmartContractModule ActiveNodeContracts (r:1 w:0)
	/// Proof Skipped: SmartContractModule ActiveNodeContracts (max_values: None, max_size: None, mode: Measured)
	/// Storage: SmartContractModule DedicatedNodesExtraFee (r:0 w:1)
	/// Proof Skipped: SmartContractModule DedicatedNodesExtraFee (max_values: None, max_size: None, mode: Measured)
	fn set_dedicated_node_extra_fee() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `733`
		//  Estimated: `4198`
		// Minimum execution time: 46_778_000 picoseconds.
		Weight::from_parts(48_978_000, 4198)
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
}

// For backwards compatibility and tests
impl WeightInfo for () {
	/// Storage: TfgridModule TwinIdByAccountID (r:1 w:0)
	/// Proof Skipped: TfgridModule TwinIdByAccountID (max_values: None, max_size: None, mode: Measured)
	/// Storage: TfgridModule Nodes (r:1 w:0)
	/// Proof Skipped: TfgridModule Nodes (max_values: None, max_size: None, mode: Measured)
	/// Storage: TfgridModule NodePower (r:1 w:0)
	/// Proof Skipped: TfgridModule NodePower (max_values: None, max_size: None, mode: Measured)
	/// Storage: TfgridModule Farms (r:1 w:1)
	/// Proof Skipped: TfgridModule Farms (max_values: None, max_size: None, mode: Measured)
	/// Storage: SmartContractModule ActiveRentContractForNode (r:1 w:0)
	/// Proof Skipped: SmartContractModule ActiveRentContractForNode (max_values: None, max_size: None, mode: Measured)
	/// Storage: SmartContractModule DedicatedNodesExtraFee (r:1 w:0)
	/// Proof Skipped: SmartContractModule DedicatedNodesExtraFee (max_values: None, max_size: None, mode: Measured)
	/// Storage: SmartContractModule ContractIDByNodeIDAndHash (r:1 w:1)
	/// Proof Skipped: SmartContractModule ContractIDByNodeIDAndHash (max_values: None, max_size: None, mode: Measured)
	/// Storage: SmartContractModule ContractID (r:1 w:1)
	/// Proof Skipped: SmartContractModule ContractID (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: SmartContractModule BillingFrequency (r:1 w:0)
	/// Proof Skipped: SmartContractModule BillingFrequency (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: SmartContractModule ContractsToBillAt (r:1 w:1)
	/// Proof Skipped: SmartContractModule ContractsToBillAt (max_values: None, max_size: None, mode: Measured)
	/// Storage: Timestamp Now (r:1 w:0)
	/// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: SmartContractModule ActiveNodeContracts (r:1 w:1)
	/// Proof Skipped: SmartContractModule ActiveNodeContracts (max_values: None, max_size: None, mode: Measured)
	/// Storage: SmartContractModule Contracts (r:0 w:1)
	/// Proof Skipped: SmartContractModule Contracts (max_values: None, max_size: None, mode: Measured)
	/// Storage: SmartContractModule ContractBillingInformationByID (r:0 w:1)
	/// Proof Skipped: SmartContractModule ContractBillingInformationByID (max_values: None, max_size: None, mode: Measured)
	/// Storage: SmartContractModule ContractLock (r:0 w:1)
	/// Proof Skipped: SmartContractModule ContractLock (max_values: None, max_size: None, mode: Measured)
	fn create_node_contract() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `868`
		//  Estimated: `4333`
		// Minimum execution time: 119_629_000 picoseconds.
		Weight::from_parts(124_124_000, 4333)
			.saturating_add(RocksDbWeight::get().reads(12_u64))
			.saturating_add(RocksDbWeight::get().writes(8_u64))
	}
	/// Storage: SmartContractModule Contracts (r:1 w:1)
	/// Proof Skipped: SmartContractModule Contracts (max_values: None, max_size: None, mode: Measured)
	/// Storage: TfgridModule Twins (r:1 w:0)
	/// Proof Skipped: TfgridModule Twins (max_values: None, max_size: None, mode: Measured)
	/// Storage: SmartContractModule ActiveNodeContracts (r:1 w:1)
	/// Proof Skipped: SmartContractModule ActiveNodeContracts (max_values: None, max_size: None, mode: Measured)
	/// Storage: SmartContractModule ContractIDByNodeIDAndHash (r:0 w:2)
	/// Proof Skipped: SmartContractModule ContractIDByNodeIDAndHash (max_values: None, max_size: None, mode: Measured)
	fn update_node_contract() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `892`
		//  Estimated: `4357`
		// Minimum execution time: 64_128_000 picoseconds.
		Weight::from_parts(67_016_000, 4357)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(4_u64))
	}
	/// Storage: SmartContractModule Contracts (r:1 w:1)
	/// Proof Skipped: SmartContractModule Contracts (max_values: None, max_size: None, mode: Measured)
	/// Storage: TfgridModule Twins (r:1 w:0)
	/// Proof Skipped: TfgridModule Twins (max_values: None, max_size: None, mode: Measured)
	/// Storage: SmartContractModule ActiveNodeContracts (r:1 w:1)
	/// Proof Skipped: SmartContractModule ActiveNodeContracts (max_values: None, max_size: None, mode: Measured)
	/// Storage: TfgridModule TwinBoundedAccountID (r:1 w:0)
	/// Proof Skipped: TfgridModule TwinBoundedAccountID (max_values: None, max_size: None, mode: Measured)
	/// Storage: Timestamp Now (r:1 w:0)
	/// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: SmartContractModule ContractLock (r:1 w:1)
	/// Proof Skipped: SmartContractModule ContractLock (max_values: None, max_size: None, mode: Measured)
	/// Storage: TfgridModule PricingPolicies (r:1 w:0)
	/// Proof Skipped: TfgridModule PricingPolicies (max_values: None, max_size: None, mode: Measured)
	/// Storage: SmartContractModule BillingFrequency (r:1 w:0)
	/// Proof Skipped: SmartContractModule BillingFrequency (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: SmartContractModule ContractsToBillAt (r:1 w:1)
	/// Proof Skipped: SmartContractModule ContractsToBillAt (max_values: None, max_size: None, mode: Measured)
	/// Storage: SmartContractModule ContractBillingInformationByID (r:0 w:1)
	/// Proof Skipped: SmartContractModule ContractBillingInformationByID (max_values: None, max_size: None, mode: Measured)
	/// Storage: SmartContractModule NodeContractResources (r:0 w:1)
	/// Proof Skipped: SmartContractModule NodeContractResources (max_values: None, max_size: None, mode: Measured)
	/// Storage: SmartContractModule ContractIDByNodeIDAndHash (r:0 w:1)
	/// Proof Skipped: SmartContractModule ContractIDByNodeIDAndHash (max_values: None, max_size: None, mode: Measured)
	fn cancel_contract() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1203`
		//  Estimated: `4668`
		// Minimum execution time: 134_164_000 picoseconds.
		Weight::from_parts(138_183_000, 4668)
			.saturating_add(RocksDbWeight::get().reads(9_u64))
			.saturating_add(RocksDbWeight::get().writes(7_u64))
	}
	/// Storage: TfgridModule TwinIdByAccountID (r:1 w:0)
	/// Proof Skipped: TfgridModule TwinIdByAccountID (max_values: None, max_size: None, mode: Measured)
	/// Storage: SmartContractModule ContractIDByNameRegistration (r:1 w:1)
	/// Proof Skipped: SmartContractModule ContractIDByNameRegistration (max_values: None, max_size: None, mode: Measured)
	/// Storage: SmartContractModule ContractID (r:1 w:1)
	/// Proof Skipped: SmartContractModule ContractID (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: SmartContractModule BillingFrequency (r:1 w:0)
	/// Proof Skipped: SmartContractModule BillingFrequency (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: SmartContractModule ContractsToBillAt (r:1 w:1)
	/// Proof Skipped: SmartContractModule ContractsToBillAt (max_values: None, max_size: None, mode: Measured)
	/// Storage: Timestamp Now (r:1 w:0)
	/// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: SmartContractModule Contracts (r:0 w:1)
	/// Proof Skipped: SmartContractModule Contracts (max_values: None, max_size: None, mode: Measured)
	/// Storage: SmartContractModule ContractLock (r:0 w:1)
	/// Proof Skipped: SmartContractModule ContractLock (max_values: None, max_size: None, mode: Measured)
	fn create_name_contract() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `340`
		//  Estimated: `3805`
		// Minimum execution time: 54_724_000 picoseconds.
		Weight::from_parts(57_496_000, 3805)
			.saturating_add(RocksDbWeight::get().reads(6_u64))
			.saturating_add(RocksDbWeight::get().writes(5_u64))
	}
	/// Storage: SmartContractModule Contracts (r:1 w:1)
	/// Proof Skipped: SmartContractModule Contracts (max_values: None, max_size: None, mode: Measured)
	/// Storage: TfgridModule Twins (r:1 w:0)
	/// Proof Skipped: TfgridModule Twins (max_values: None, max_size: None, mode: Measured)
	/// Storage: TfgridModule TwinBoundedAccountID (r:1 w:0)
	/// Proof Skipped: TfgridModule TwinBoundedAccountID (max_values: None, max_size: None, mode: Measured)
	/// Storage: Timestamp Now (r:1 w:0)
	/// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: SmartContractModule ContractLock (r:1 w:1)
	/// Proof Skipped: SmartContractModule ContractLock (max_values: None, max_size: None, mode: Measured)
	/// Storage: TfgridModule PricingPolicies (r:1 w:0)
	/// Proof Skipped: TfgridModule PricingPolicies (max_values: None, max_size: None, mode: Measured)
	/// Storage: SmartContractModule BillingFrequency (r:1 w:0)
	/// Proof Skipped: SmartContractModule BillingFrequency (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: SmartContractModule ContractsToBillAt (r:1 w:1)
	/// Proof Skipped: SmartContractModule ContractsToBillAt (max_values: None, max_size: None, mode: Measured)
	/// Storage: SmartContractModule ContractIDByNameRegistration (r:0 w:1)
	/// Proof Skipped: SmartContractModule ContractIDByNameRegistration (max_values: None, max_size: None, mode: Measured)
	fn cancel_name_contract() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `919`
		//  Estimated: `4384`
		// Minimum execution time: 101_753_000 picoseconds.
		Weight::from_parts(105_128_000, 4384)
			.saturating_add(RocksDbWeight::get().reads(8_u64))
			.saturating_add(RocksDbWeight::get().writes(4_u64))
	}
	/// Storage: TfgridModule TwinIdByAccountID (r:1 w:0)
	/// Proof Skipped: TfgridModule TwinIdByAccountID (max_values: None, max_size: None, mode: Measured)
	/// Storage: TfgridModule NodeIdByTwinID (r:1 w:0)
	/// Proof Skipped: TfgridModule NodeIdByTwinID (max_values: None, max_size: None, mode: Measured)
	/// Storage: TfgridModule Nodes (r:1 w:0)
	/// Proof Skipped: TfgridModule Nodes (max_values: None, max_size: None, mode: Measured)
	/// Storage: TfgridModule Farms (r:1 w:0)
	/// Proof Skipped: TfgridModule Farms (max_values: None, max_size: None, mode: Measured)
	/// Storage: TfgridModule PricingPolicies (r:1 w:0)
	/// Proof Skipped: TfgridModule PricingPolicies (max_values: None, max_size: None, mode: Measured)
	/// Storage: SmartContractModule Contracts (r:1 w:0)
	/// Proof Skipped: SmartContractModule Contracts (max_values: None, max_size: None, mode: Measured)
	/// Storage: SmartContractModule ContractBillingInformationByID (r:1 w:1)
	/// Proof Skipped: SmartContractModule ContractBillingInformationByID (max_values: None, max_size: None, mode: Measured)
	fn add_nru_reports() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1292`
		//  Estimated: `4757`
		// Minimum execution time: 77_126_000 picoseconds.
		Weight::from_parts(79_222_000, 4757)
			.saturating_add(RocksDbWeight::get().reads(7_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: TfgridModule TwinIdByAccountID (r:1 w:0)
	/// Proof Skipped: TfgridModule TwinIdByAccountID (max_values: None, max_size: None, mode: Measured)
	/// Storage: TfgridModule NodeIdByTwinID (r:1 w:0)
	/// Proof Skipped: TfgridModule NodeIdByTwinID (max_values: None, max_size: None, mode: Measured)
	/// Storage: SmartContractModule Contracts (r:1 w:0)
	/// Proof Skipped: SmartContractModule Contracts (max_values: None, max_size: None, mode: Measured)
	/// Storage: SmartContractModule NodeContractResources (r:0 w:1)
	/// Proof Skipped: SmartContractModule NodeContractResources (max_values: None, max_size: None, mode: Measured)
	fn report_contract_resources() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `771`
		//  Estimated: `4236`
		// Minimum execution time: 47_460_000 picoseconds.
		Weight::from_parts(48_914_000, 4236)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: SmartContractModule ActiveRentContractForNode (r:1 w:1)
	/// Proof Skipped: SmartContractModule ActiveRentContractForNode (max_values: None, max_size: None, mode: Measured)
	/// Storage: TfgridModule Nodes (r:1 w:0)
	/// Proof Skipped: TfgridModule Nodes (max_values: None, max_size: None, mode: Measured)
	/// Storage: TfgridModule Farms (r:1 w:0)
	/// Proof Skipped: TfgridModule Farms (max_values: None, max_size: None, mode: Measured)
	/// Storage: TfgridModule NodePower (r:1 w:0)
	/// Proof Skipped: TfgridModule NodePower (max_values: None, max_size: None, mode: Measured)
	/// Storage: SmartContractModule ActiveNodeContracts (r:1 w:0)
	/// Proof Skipped: SmartContractModule ActiveNodeContracts (max_values: None, max_size: None, mode: Measured)
	/// Storage: TfgridModule TwinIdByAccountID (r:1 w:0)
	/// Proof Skipped: TfgridModule TwinIdByAccountID (max_values: None, max_size: None, mode: Measured)
	/// Storage: SmartContractModule ContractID (r:1 w:1)
	/// Proof Skipped: SmartContractModule ContractID (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: SmartContractModule BillingFrequency (r:1 w:0)
	/// Proof Skipped: SmartContractModule BillingFrequency (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: SmartContractModule ContractsToBillAt (r:1 w:1)
	/// Proof Skipped: SmartContractModule ContractsToBillAt (max_values: None, max_size: None, mode: Measured)
	/// Storage: Timestamp Now (r:1 w:0)
	/// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: SmartContractModule Contracts (r:0 w:1)
	/// Proof Skipped: SmartContractModule Contracts (max_values: None, max_size: None, mode: Measured)
	/// Storage: SmartContractModule ContractLock (r:0 w:1)
	/// Proof Skipped: SmartContractModule ContractLock (max_values: None, max_size: None, mode: Measured)
	fn create_rent_contract() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `868`
		//  Estimated: `4333`
		// Minimum execution time: 78_140_000 picoseconds.
		Weight::from_parts(81_100_000, 4333)
			.saturating_add(RocksDbWeight::get().reads(10_u64))
			.saturating_add(RocksDbWeight::get().writes(5_u64))
	}
	/// Storage: SmartContractModule Contracts (r:1 w:1)
	/// Proof Skipped: SmartContractModule Contracts (max_values: None, max_size: None, mode: Measured)
	/// Storage: TfgridModule Twins (r:1 w:0)
	/// Proof Skipped: TfgridModule Twins (max_values: None, max_size: None, mode: Measured)
	/// Storage: SmartContractModule ActiveNodeContracts (r:1 w:0)
	/// Proof Skipped: SmartContractModule ActiveNodeContracts (max_values: None, max_size: None, mode: Measured)
	/// Storage: TfgridModule TwinBoundedAccountID (r:1 w:0)
	/// Proof Skipped: TfgridModule TwinBoundedAccountID (max_values: None, max_size: None, mode: Measured)
	/// Storage: Timestamp Now (r:1 w:0)
	/// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: SmartContractModule ContractLock (r:1 w:1)
	/// Proof Skipped: SmartContractModule ContractLock (max_values: None, max_size: None, mode: Measured)
	/// Storage: TfgridModule PricingPolicies (r:1 w:0)
	/// Proof Skipped: TfgridModule PricingPolicies (max_values: None, max_size: None, mode: Measured)
	/// Storage: SmartContractModule DedicatedNodesExtraFee (r:1 w:0)
	/// Proof Skipped: SmartContractModule DedicatedNodesExtraFee (max_values: None, max_size: None, mode: Measured)
	/// Storage: SmartContractModule BillingFrequency (r:1 w:0)
	/// Proof Skipped: SmartContractModule BillingFrequency (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: SmartContractModule ContractsToBillAt (r:1 w:1)
	/// Proof Skipped: SmartContractModule ContractsToBillAt (max_values: None, max_size: None, mode: Measured)
	/// Storage: SmartContractModule ActiveRentContractForNode (r:0 w:1)
	/// Proof Skipped: SmartContractModule ActiveRentContractForNode (max_values: None, max_size: None, mode: Measured)
	fn cancel_rent_contract() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1071`
		//  Estimated: `4536`
		// Minimum execution time: 114_334_000 picoseconds.
		Weight::from_parts(118_126_000, 4536)
			.saturating_add(RocksDbWeight::get().reads(10_u64))
			.saturating_add(RocksDbWeight::get().writes(4_u64))
	}
	/// Storage: SmartContractModule SolutionProviderID (r:1 w:1)
	/// Proof Skipped: SmartContractModule SolutionProviderID (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: SmartContractModule SolutionProviders (r:0 w:1)
	/// Proof Skipped: SmartContractModule SolutionProviders (max_values: None, max_size: None, mode: Measured)
	fn create_solution_provider() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `37`
		//  Estimated: `1522`
		// Minimum execution time: 24_361_000 picoseconds.
		Weight::from_parts(25_532_000, 1522)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: SmartContractModule SolutionProviders (r:1 w:1)
	/// Proof Skipped: SmartContractModule SolutionProviders (max_values: None, max_size: None, mode: Measured)
	fn approve_solution_provider() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `215`
		//  Estimated: `3680`
		// Minimum execution time: 28_651_000 picoseconds.
		Weight::from_parts(29_486_000, 3680)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: SmartContractModule Contracts (r:1 w:0)
	/// Proof Skipped: SmartContractModule Contracts (max_values: None, max_size: None, mode: Measured)
	/// Storage: TfgridModule Twins (r:1 w:0)
	/// Proof Skipped: TfgridModule Twins (max_values: None, max_size: None, mode: Measured)
	/// Storage: System Account (r:1 w:0)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// Storage: TfgridModule TwinBoundedAccountID (r:1 w:0)
	/// Proof Skipped: TfgridModule TwinBoundedAccountID (max_values: None, max_size: None, mode: Measured)
	/// Storage: Timestamp Now (r:1 w:0)
	/// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: SmartContractModule ContractLock (r:1 w:0)
	/// Proof Skipped: SmartContractModule ContractLock (max_values: None, max_size: None, mode: Measured)
	/// Storage: TfgridModule PricingPolicies (r:1 w:0)
	/// Proof Skipped: TfgridModule PricingPolicies (max_values: None, max_size: None, mode: Measured)
	fn bill_contract_for_block() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1216`
		//  Estimated: `4681`
		// Minimum execution time: 56_839_000 picoseconds.
		Weight::from_parts(58_569_000, 4681)
			.saturating_add(RocksDbWeight::get().reads(7_u64))
	}
	/// Storage: TfgridModule TwinIdByAccountID (r:2 w:0)
	/// Proof Skipped: TfgridModule TwinIdByAccountID (max_values: None, max_size: None, mode: Measured)
	/// Storage: SmartContractModule ServiceContractID (r:1 w:1)
	/// Proof Skipped: SmartContractModule ServiceContractID (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: SmartContractModule ServiceContracts (r:0 w:1)
	/// Proof Skipped: SmartContractModule ServiceContracts (max_values: None, max_size: None, mode: Measured)
	fn service_contract_create() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `395`
		//  Estimated: `6335`
		// Minimum execution time: 40_172_000 picoseconds.
		Weight::from_parts(41_719_000, 6335)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: TfgridModule TwinIdByAccountID (r:1 w:0)
	/// Proof Skipped: TfgridModule TwinIdByAccountID (max_values: None, max_size: None, mode: Measured)
	/// Storage: SmartContractModule ServiceContracts (r:1 w:1)
	/// Proof Skipped: SmartContractModule ServiceContracts (max_values: None, max_size: None, mode: Measured)
	fn service_contract_set_metadata() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `489`
		//  Estimated: `3954`
		// Minimum execution time: 35_442_000 picoseconds.
		Weight::from_parts(36_518_000, 3954)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: TfgridModule TwinIdByAccountID (r:1 w:0)
	/// Proof Skipped: TfgridModule TwinIdByAccountID (max_values: None, max_size: None, mode: Measured)
	/// Storage: SmartContractModule ServiceContracts (r:1 w:1)
	/// Proof Skipped: SmartContractModule ServiceContracts (max_values: None, max_size: None, mode: Measured)
	fn service_contract_set_fees() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `489`
		//  Estimated: `3954`
		// Minimum execution time: 34_663_000 picoseconds.
		Weight::from_parts(35_371_000, 3954)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: TfgridModule TwinIdByAccountID (r:1 w:0)
	/// Proof Skipped: TfgridModule TwinIdByAccountID (max_values: None, max_size: None, mode: Measured)
	/// Storage: SmartContractModule ServiceContracts (r:1 w:1)
	/// Proof Skipped: SmartContractModule ServiceContracts (max_values: None, max_size: None, mode: Measured)
	fn service_contract_approve() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `502`
		//  Estimated: `3967`
		// Minimum execution time: 34_967_000 picoseconds.
		Weight::from_parts(36_503_000, 3967)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: TfgridModule TwinIdByAccountID (r:1 w:0)
	/// Proof Skipped: TfgridModule TwinIdByAccountID (max_values: None, max_size: None, mode: Measured)
	/// Storage: SmartContractModule ServiceContracts (r:1 w:1)
	/// Proof Skipped: SmartContractModule ServiceContracts (max_values: None, max_size: None, mode: Measured)
	fn service_contract_reject() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `502`
		//  Estimated: `3967`
		// Minimum execution time: 36_210_000 picoseconds.
		Weight::from_parts(37_826_000, 3967)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: TfgridModule TwinIdByAccountID (r:1 w:0)
	/// Proof Skipped: TfgridModule TwinIdByAccountID (max_values: None, max_size: None, mode: Measured)
	/// Storage: SmartContractModule ServiceContracts (r:1 w:1)
	/// Proof Skipped: SmartContractModule ServiceContracts (max_values: None, max_size: None, mode: Measured)
	fn service_contract_cancel() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `502`
		//  Estimated: `3967`
		// Minimum execution time: 33_426_000 picoseconds.
		Weight::from_parts(34_600_000, 3967)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: TfgridModule TwinIdByAccountID (r:1 w:0)
	/// Proof Skipped: TfgridModule TwinIdByAccountID (max_values: None, max_size: None, mode: Measured)
	/// Storage: SmartContractModule ServiceContracts (r:1 w:1)
	/// Proof Skipped: SmartContractModule ServiceContracts (max_values: None, max_size: None, mode: Measured)
	/// Storage: Timestamp Now (r:1 w:0)
	/// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: TfgridModule Twins (r:2 w:0)
	/// Proof Skipped: TfgridModule Twins (max_values: None, max_size: None, mode: Measured)
	/// Storage: System Account (r:1 w:0)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	fn service_contract_bill() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `841`
		//  Estimated: `6781`
		// Minimum execution time: 61_064_000 picoseconds.
		Weight::from_parts(64_267_000, 6781)
			.saturating_add(RocksDbWeight::get().reads(6_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: SmartContractModule BillingFrequency (r:1 w:1)
	/// Proof Skipped: SmartContractModule BillingFrequency (max_values: Some(1), max_size: None, mode: Measured)
	fn change_billing_frequency() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `37`
		//  Estimated: `1522`
		// Minimum execution time: 17_066_000 picoseconds.
		Weight::from_parts(17_649_000, 1522)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: SmartContractModule SolutionProviders (r:1 w:0)
	/// Proof Skipped: SmartContractModule SolutionProviders (max_values: None, max_size: None, mode: Measured)
	/// Storage: SmartContractModule Contracts (r:1 w:1)
	/// Proof Skipped: SmartContractModule Contracts (max_values: None, max_size: None, mode: Measured)
	/// Storage: TfgridModule TwinIdByAccountID (r:1 w:0)
	/// Proof Skipped: TfgridModule TwinIdByAccountID (max_values: None, max_size: None, mode: Measured)
	fn attach_solution_provider_id() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `971`
		//  Estimated: `4436`
		// Minimum execution time: 44_207_000 picoseconds.
		Weight::from_parts(46_180_000, 4436)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: TfgridModule TwinIdByAccountID (r:1 w:0)
	/// Proof Skipped: TfgridModule TwinIdByAccountID (max_values: None, max_size: None, mode: Measured)
	/// Storage: TfgridModule Nodes (r:1 w:0)
	/// Proof Skipped: TfgridModule Nodes (max_values: None, max_size: None, mode: Measured)
	/// Storage: TfgridModule Farms (r:1 w:0)
	/// Proof Skipped: TfgridModule Farms (max_values: None, max_size: None, mode: Measured)
	/// Storage: SmartContractModule ActiveRentContractForNode (r:1 w:0)
	/// Proof Skipped: SmartContractModule ActiveRentContractForNode (max_values: None, max_size: None, mode: Measured)
	/// Storage: SmartContractModule ActiveNodeContracts (r:1 w:0)
	/// Proof Skipped: SmartContractModule ActiveNodeContracts (max_values: None, max_size: None, mode: Measured)
	/// Storage: SmartContractModule DedicatedNodesExtraFee (r:0 w:1)
	/// Proof Skipped: SmartContractModule DedicatedNodesExtraFee (max_values: None, max_size: None, mode: Measured)
	fn set_dedicated_node_extra_fee() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `733`
		//  Estimated: `4198`
		// Minimum execution time: 46_778_000 picoseconds.
		Weight::from_parts(48_978_000, 4198)
			.saturating_add(RocksDbWeight::get().reads(5_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
}
