FROM node:14-alpine 

RUN mkdir -p /home/hydra-builder && chown -R node:node /home/hydra-builder

WORKDIR /home/hydra-builder

ADD ./mappings ./mappings
ADD ./types ./types
ADD ./generated ./generated
COPY ./*.yml ./
COPY ./*.json ./
COPY ./*.graphql ./
COPY ./.env ./

RUN yarn --frozen-lockfile

CMD ["yarn", "processor:migrate"]
CMD ["yarn", "processor:start"]