FROM node:14-alpine 

RUN mkdir -p /home/hydra-builder && chown -R node:node /home/hydra-builder

WORKDIR /home/hydra-builder

ADD ./mappings ./mappings
ADD ./chain ./chain
ADD ./generated ./generated
COPY ./*.yml ./
COPY ./*.json ./
COPY ./*.graphql ./
COPY ./.env ./
COPY ./init-countries.js ./

RUN yarn --frozen-lockfile

CMD ["yarn", "query-node:start"]