
//! Autogenerated weights for pallet_tfgrid
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2026-02-26, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `f66f16d01624`, CPU: `DO-Regular`
//! EXECUTION: , WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
// ./target/production/tfchain
// benchmark
// pallet
// --chain=dev
// --wasm-execution=compiled
// --pallet=pallet-tfgrid
// --extrinsic=*
// --steps=50
// --repeat=20
// --heap-pages=409
// --output
// ./pallets/pallet-tfgrid/src/weights.rs
// --template
// ./.maintain/frame-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for pallet_tfgrid.
pub trait WeightInfo {
	fn set_storage_version() -> Weight;
	fn create_farm() -> Weight;
	fn update_farm() -> Weight;
	fn add_stellar_payout_v2address() -> Weight;
	fn set_farm_certification() -> Weight;
	fn add_farm_ip() -> Weight;
	fn remove_farm_ip() -> Weight;
	fn create_node() -> Weight;
	fn update_node() -> Weight;
	fn set_node_certification() -> Weight;
	fn report_uptime() -> Weight;
	fn add_node_public_config() -> Weight;
	fn delete_node() -> Weight;
	fn create_twin() -> Weight;
	fn update_twin() -> Weight;
	fn create_pricing_policy() -> Weight;
	fn update_pricing_policy() -> Weight;
	fn create_farming_policy() -> Weight;
	fn user_accept_tc() -> Weight;
	fn request_twin_transfer() -> Weight;
	fn accept_twin_transfer() -> Weight;
	fn cancel_twin_transfer() -> Weight;
	fn delete_node_farm() -> Weight;
	fn set_farm_dedicated() -> Weight;
	fn force_reset_farm_ip() -> Weight;
	fn set_connection_price() -> Weight;
	fn add_node_certifier() -> Weight;
	fn remove_node_certifier() -> Weight;
	fn update_farming_policy() -> Weight;
	fn attach_policy_to_farm() -> Weight;
	fn set_zos_version() -> Weight;
	fn change_power_state() -> Weight;
	fn change_power_target() -> Weight;
	fn bond_twin_account() -> Weight;
	fn report_uptime_v2() -> Weight;
	fn opt_out_of_v3_billing() -> Weight;
	fn set_node_v3_opt_out_metadata() -> Weight;
	fn add_twin_admin(n: u32, ) -> Weight;
	fn remove_twin_admin(n: u32, ) -> Weight;
}

/// Weights for pallet_tfgrid using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `TfgridModule::PalletVersion` (r:0 w:1)
	/// Proof: `TfgridModule::PalletVersion` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn set_storage_version() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 7_786_000 picoseconds.
		Weight::from_parts(8_665_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `TfgridModule::TwinIdByAccountID` (r:1 w:0)
	/// Proof: `TfgridModule::TwinIdByAccountID` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TfgridModule::Twins` (r:1 w:0)
	/// Proof: `TfgridModule::Twins` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TfgridModule::FarmIdByName` (r:1 w:1)
	/// Proof: `TfgridModule::FarmIdByName` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TfgridModule::FarmID` (r:1 w:1)
	/// Proof: `TfgridModule::FarmID` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `TfgridModule::Farms` (r:0 w:1)
	/// Proof: `TfgridModule::Farms` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn create_farm() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `496`
		//  Estimated: `3961`
		// Minimum execution time: 38_369_000 picoseconds.
		Weight::from_parts(54_973_000, 3961)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `TfgridModule::TwinIdByAccountID` (r:1 w:0)
	/// Proof: `TfgridModule::TwinIdByAccountID` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TfgridModule::Farms` (r:1 w:1)
	/// Proof: `TfgridModule::Farms` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TfgridModule::FarmIdByName` (r:1 w:2)
	/// Proof: `TfgridModule::FarmIdByName` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn update_farm() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `507`
		//  Estimated: `3972`
		// Minimum execution time: 59_376_000 picoseconds.
		Weight::from_parts(60_402_000, 3972)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `TfgridModule::TwinIdByAccountID` (r:1 w:0)
	/// Proof: `TfgridModule::TwinIdByAccountID` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TfgridModule::Farms` (r:1 w:0)
	/// Proof: `TfgridModule::Farms` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TfgridModule::FarmPayoutV2AddressByFarmID` (r:0 w:1)
	/// Proof: `TfgridModule::FarmPayoutV2AddressByFarmID` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn add_stellar_payout_v2address() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `453`
		//  Estimated: `3918`
		// Minimum execution time: 29_793_000 picoseconds.
		Weight::from_parts(30_517_000, 3918)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `TfgridModule::Farms` (r:1 w:1)
	/// Proof: `TfgridModule::Farms` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn set_farm_certification() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `412`
		//  Estimated: `3877`
		// Minimum execution time: 24_881_000 picoseconds.
		Weight::from_parts(25_611_000, 3877)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `TfgridModule::Farms` (r:1 w:1)
	/// Proof: `TfgridModule::Farms` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TfgridModule::Twins` (r:1 w:0)
	/// Proof: `TfgridModule::Twins` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn add_farm_ip() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `569`
		//  Estimated: `4034`
		// Minimum execution time: 33_632_000 picoseconds.
		Weight::from_parts(46_239_000, 4034)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `TfgridModule::Farms` (r:1 w:1)
	/// Proof: `TfgridModule::Farms` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TfgridModule::Twins` (r:1 w:0)
	/// Proof: `TfgridModule::Twins` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn remove_farm_ip() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `569`
		//  Estimated: `4034`
		// Minimum execution time: 32_071_000 picoseconds.
		Weight::from_parts(48_623_000, 4034)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `TfgridModule::Farms` (r:1 w:0)
	/// Proof: `TfgridModule::Farms` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TfgridModule::TwinIdByAccountID` (r:1 w:0)
	/// Proof: `TfgridModule::TwinIdByAccountID` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TfgridModule::NodeIdByTwinID` (r:1 w:1)
	/// Proof: `TfgridModule::NodeIdByTwinID` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TfgridModule::NodeID` (r:1 w:1)
	/// Proof: `TfgridModule::NodeID` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `TfgridModule::ConnectionPrice` (r:1 w:0)
	/// Proof: `TfgridModule::ConnectionPrice` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `TfgridModule::FarmingPoliciesMap` (r:4 w:0)
	/// Proof: `TfgridModule::FarmingPoliciesMap` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TfgridModule::NodesByFarmID` (r:1 w:1)
	/// Proof: `TfgridModule::NodesByFarmID` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Dao::FarmWeight` (r:1 w:1)
	/// Proof: `Dao::FarmWeight` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TfgridModule::Nodes` (r:0 w:1)
	/// Proof: `TfgridModule::Nodes` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn create_node() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `905`
		//  Estimated: `11795`
		// Minimum execution time: 90_616_000 picoseconds.
		Weight::from_parts(135_619_000, 11795)
			.saturating_add(T::DbWeight::get().reads(12_u64))
			.saturating_add(T::DbWeight::get().writes(5_u64))
	}
	/// Storage: `TfgridModule::Nodes` (r:1 w:1)
	/// Proof: `TfgridModule::Nodes` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TfgridModule::TwinIdByAccountID` (r:1 w:0)
	/// Proof: `TfgridModule::TwinIdByAccountID` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TfgridModule::Farms` (r:1 w:0)
	/// Proof: `TfgridModule::Farms` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Dao::FarmWeight` (r:1 w:1)
	/// Proof: `Dao::FarmWeight` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn update_node() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `661`
		//  Estimated: `4126`
		// Minimum execution time: 49_993_000 picoseconds.
		Weight::from_parts(51_155_000, 4126)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `TfgridModule::Nodes` (r:1 w:1)
	/// Proof: `TfgridModule::Nodes` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TfgridModule::FarmingPoliciesMap` (r:4 w:0)
	/// Proof: `TfgridModule::FarmingPoliciesMap` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TfgridModule::Farms` (r:1 w:0)
	/// Proof: `TfgridModule::Farms` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn set_node_certification() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `956`
		//  Estimated: `11846`
		// Minimum execution time: 64_630_000 picoseconds.
		Weight::from_parts(65_771_000, 11846)
			.saturating_add(T::DbWeight::get().reads(6_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `TfgridModule::TwinIdByAccountID` (r:1 w:0)
	/// Proof: `TfgridModule::TwinIdByAccountID` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TfgridModule::NodeIdByTwinID` (r:1 w:0)
	/// Proof: `TfgridModule::NodeIdByTwinID` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TfgridModule::Nodes` (r:1 w:0)
	/// Proof: `TfgridModule::Nodes` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn report_uptime() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `454`
		//  Estimated: `3919`
		// Minimum execution time: 34_209_000 picoseconds.
		Weight::from_parts(35_067_000, 3919)
			.saturating_add(T::DbWeight::get().reads(4_u64))
	}
	/// Storage: `TfgridModule::Farms` (r:1 w:0)
	/// Proof: `TfgridModule::Farms` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TfgridModule::Twins` (r:1 w:0)
	/// Proof: `TfgridModule::Twins` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TfgridModule::Nodes` (r:1 w:1)
	/// Proof: `TfgridModule::Nodes` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn add_node_public_config() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `779`
		//  Estimated: `4244`
		// Minimum execution time: 45_290_000 picoseconds.
		Weight::from_parts(46_244_000, 4244)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `TfgridModule::Nodes` (r:1 w:1)
	/// Proof: `TfgridModule::Nodes` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TfgridModule::TwinIdByAccountID` (r:1 w:0)
	/// Proof: `TfgridModule::TwinIdByAccountID` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TfgridModule::NodesByFarmID` (r:1 w:1)
	/// Proof: `TfgridModule::NodesByFarmID` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SmartContractModule::ActiveNodeContracts` (r:1 w:0)
	/// Proof: `SmartContractModule::ActiveNodeContracts` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SmartContractModule::ActiveRentContractForNode` (r:1 w:0)
	/// Proof: `SmartContractModule::ActiveRentContractForNode` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Dao::FarmWeight` (r:1 w:1)
	/// Proof: `Dao::FarmWeight` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TfgridModule::NodeV3BillingOptOut` (r:0 w:1)
	/// Proof: `TfgridModule::NodeV3BillingOptOut` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn delete_node() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `682`
		//  Estimated: `4147`
		// Minimum execution time: 53_319_000 picoseconds.
		Weight::from_parts(77_405_000, 4147)
			.saturating_add(T::DbWeight::get().reads(6_u64))
			.saturating_add(T::DbWeight::get().writes(4_u64))
	}
	/// Storage: `TfgridModule::UsersTermsAndConditions` (r:1 w:0)
	/// Proof: `TfgridModule::UsersTermsAndConditions` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TfgridModule::TwinIdByAccountID` (r:1 w:1)
	/// Proof: `TfgridModule::TwinIdByAccountID` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TfgridModule::TwinID` (r:1 w:1)
	/// Proof: `TfgridModule::TwinID` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `TfgridModule::Twins` (r:0 w:1)
	/// Proof: `TfgridModule::Twins` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn create_twin() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `235`
		//  Estimated: `3700`
		// Minimum execution time: 27_879_000 picoseconds.
		Weight::from_parts(28_497_000, 3700)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `TfgridModule::TwinIdByAccountID` (r:1 w:0)
	/// Proof: `TfgridModule::TwinIdByAccountID` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TfgridModule::Twins` (r:1 w:1)
	/// Proof: `TfgridModule::Twins` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn update_twin() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `428`
		//  Estimated: `3893`
		// Minimum execution time: 28_399_000 picoseconds.
		Weight::from_parts(29_229_000, 3893)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `TfgridModule::PricingPolicyIdByName` (r:1 w:1)
	/// Proof: `TfgridModule::PricingPolicyIdByName` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TfgridModule::PricingPolicyID` (r:1 w:1)
	/// Proof: `TfgridModule::PricingPolicyID` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `TfgridModule::PricingPolicies` (r:0 w:1)
	/// Proof: `TfgridModule::PricingPolicies` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn create_pricing_policy() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `134`
		//  Estimated: `3599`
		// Minimum execution time: 23_679_000 picoseconds.
		Weight::from_parts(24_511_000, 3599)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `TfgridModule::PricingPolicies` (r:1 w:1)
	/// Proof: `TfgridModule::PricingPolicies` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TfgridModule::PricingPolicyIdByName` (r:1 w:1)
	/// Proof: `TfgridModule::PricingPolicyIdByName` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TfgridModule::PricingPolicyID` (r:0 w:1)
	/// Proof: `TfgridModule::PricingPolicyID` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn update_pricing_policy() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `382`
		//  Estimated: `3847`
		// Minimum execution time: 31_336_000 picoseconds.
		Weight::from_parts(33_796_000, 3847)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `TfgridModule::FarmingPolicyID` (r:1 w:1)
	/// Proof: `TfgridModule::FarmingPolicyID` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `TfgridModule::FarmingPoliciesMap` (r:0 w:1)
	/// Proof: `TfgridModule::FarmingPoliciesMap` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn create_farming_policy() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `134`
		//  Estimated: `1619`
		// Minimum execution time: 19_812_000 picoseconds.
		Weight::from_parts(20_457_000, 1619)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `TfgridModule::UsersTermsAndConditions` (r:1 w:1)
	/// Proof: `TfgridModule::UsersTermsAndConditions` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn user_accept_tc() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `140`
		//  Estimated: `3605`
		// Minimum execution time: 14_177_000 picoseconds.
		Weight::from_parts(14_759_000, 3605)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `TfgridModule::TwinIdByAccountID` (r:2 w:0)
	/// Proof: `TfgridModule::TwinIdByAccountID` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TfgridModule::Twins` (r:1 w:0)
	/// Proof: `TfgridModule::Twins` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TfgridModule::UsersTermsAndConditions` (r:1 w:0)
	/// Proof: `TfgridModule::UsersTermsAndConditions` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TfgridModule::PendingTransferByTwin` (r:1 w:1)
	/// Proof: `TfgridModule::PendingTransferByTwin` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TfgridModule::TwinTransferRequestID` (r:1 w:1)
	/// Proof: `TfgridModule::TwinTransferRequestID` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `TfgridModule::TwinTransferRequests` (r:0 w:1)
	/// Proof: `TfgridModule::TwinTransferRequests` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn request_twin_transfer() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `527`
		//  Estimated: `6467`
		// Minimum execution time: 44_601_000 picoseconds.
		Weight::from_parts(45_304_000, 6467)
			.saturating_add(T::DbWeight::get().reads(6_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `TfgridModule::TwinTransferRequests` (r:1 w:1)
	/// Proof: `TfgridModule::TwinTransferRequests` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TfgridModule::Twins` (r:1 w:1)
	/// Proof: `TfgridModule::Twins` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TfgridModule::TwinIdByAccountID` (r:1 w:2)
	/// Proof: `TfgridModule::TwinIdByAccountID` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TfgridModule::PendingTransferByTwin` (r:0 w:1)
	/// Proof: `TfgridModule::PendingTransferByTwin` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn accept_twin_transfer() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `605`
		//  Estimated: `4070`
		// Minimum execution time: 50_032_000 picoseconds.
		Weight::from_parts(51_023_000, 4070)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(5_u64))
	}
	/// Storage: `TfgridModule::TwinTransferRequests` (r:1 w:1)
	/// Proof: `TfgridModule::TwinTransferRequests` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TfgridModule::PendingTransferByTwin` (r:0 w:1)
	/// Proof: `TfgridModule::PendingTransferByTwin` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn cancel_twin_transfer() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `403`
		//  Estimated: `3868`
		// Minimum execution time: 25_233_000 picoseconds.
		Weight::from_parts(26_372_000, 3868)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `TfgridModule::TwinIdByAccountID` (r:1 w:0)
	/// Proof: `TfgridModule::TwinIdByAccountID` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TfgridModule::Nodes` (r:1 w:1)
	/// Proof: `TfgridModule::Nodes` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TfgridModule::Farms` (r:1 w:0)
	/// Proof: `TfgridModule::Farms` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TfgridModule::NodesByFarmID` (r:1 w:1)
	/// Proof: `TfgridModule::NodesByFarmID` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SmartContractModule::ActiveNodeContracts` (r:1 w:0)
	/// Proof: `SmartContractModule::ActiveNodeContracts` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SmartContractModule::ActiveRentContractForNode` (r:1 w:0)
	/// Proof: `SmartContractModule::ActiveRentContractForNode` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Dao::FarmWeight` (r:1 w:1)
	/// Proof: `Dao::FarmWeight` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TfgridModule::NodeIdByTwinID` (r:0 w:1)
	/// Proof: `TfgridModule::NodeIdByTwinID` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn delete_node_farm() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `828`
		//  Estimated: `4293`
		// Minimum execution time: 62_557_000 picoseconds.
		Weight::from_parts(94_567_000, 4293)
			.saturating_add(T::DbWeight::get().reads(7_u64))
			.saturating_add(T::DbWeight::get().writes(4_u64))
	}
	/// Storage: `TfgridModule::Farms` (r:1 w:1)
	/// Proof: `TfgridModule::Farms` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn set_farm_dedicated() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `412`
		//  Estimated: `3877`
		// Minimum execution time: 36_903_000 picoseconds.
		Weight::from_parts(38_864_000, 3877)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `TfgridModule::Farms` (r:1 w:1)
	/// Proof: `TfgridModule::Farms` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn force_reset_farm_ip() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `412`
		//  Estimated: `3877`
		// Minimum execution time: 25_914_000 picoseconds.
		Weight::from_parts(27_545_000, 3877)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `TfgridModule::ConnectionPrice` (r:0 w:1)
	/// Proof: `TfgridModule::ConnectionPrice` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn set_connection_price() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 11_697_000 picoseconds.
		Weight::from_parts(18_668_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `TfgridModule::AllowedNodeCertifiers` (r:1 w:1)
	/// Proof: `TfgridModule::AllowedNodeCertifiers` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn add_node_certifier() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `355`
		//  Estimated: `1840`
		// Minimum execution time: 19_097_000 picoseconds.
		Weight::from_parts(30_428_000, 1840)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `TfgridModule::AllowedNodeCertifiers` (r:1 w:1)
	/// Proof: `TfgridModule::AllowedNodeCertifiers` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn remove_node_certifier() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `413`
		//  Estimated: `1898`
		// Minimum execution time: 28_443_000 picoseconds.
		Weight::from_parts(39_335_000, 1898)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `TfgridModule::FarmingPoliciesMap` (r:1 w:1)
	/// Proof: `TfgridModule::FarmingPoliciesMap` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn update_farming_policy() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `294`
		//  Estimated: `3759`
		// Minimum execution time: 25_275_000 picoseconds.
		Weight::from_parts(25_914_000, 3759)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `TfgridModule::FarmingPoliciesMap` (r:1 w:0)
	/// Proof: `TfgridModule::FarmingPoliciesMap` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TfgridModule::Farms` (r:1 w:1)
	/// Proof: `TfgridModule::Farms` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TfgridModule::NodesByFarmID` (r:1 w:0)
	/// Proof: `TfgridModule::NodesByFarmID` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn attach_policy_to_farm() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `572`
		//  Estimated: `4037`
		// Minimum execution time: 42_039_000 picoseconds.
		Weight::from_parts(42_748_000, 4037)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `TfgridModule::ZosVersion` (r:1 w:1)
	/// Proof: `TfgridModule::ZosVersion` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn set_zos_version() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `134`
		//  Estimated: `1619`
		// Minimum execution time: 15_354_000 picoseconds.
		Weight::from_parts(16_232_000, 1619)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `TfgridModule::TwinIdByAccountID` (r:1 w:0)
	/// Proof: `TfgridModule::TwinIdByAccountID` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TfgridModule::NodeIdByTwinID` (r:1 w:0)
	/// Proof: `TfgridModule::NodeIdByTwinID` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TfgridModule::Nodes` (r:1 w:0)
	/// Proof: `TfgridModule::Nodes` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TfgridModule::NodePower` (r:1 w:1)
	/// Proof: `TfgridModule::NodePower` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn change_power_state() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `621`
		//  Estimated: `4086`
		// Minimum execution time: 41_685_000 picoseconds.
		Weight::from_parts(43_574_000, 4086)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `TfgridModule::TwinIdByAccountID` (r:1 w:0)
	/// Proof: `TfgridModule::TwinIdByAccountID` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TfgridModule::Nodes` (r:1 w:0)
	/// Proof: `TfgridModule::Nodes` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TfgridModule::Farms` (r:1 w:0)
	/// Proof: `TfgridModule::Farms` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SmartContractModule::ActiveNodeContracts` (r:1 w:0)
	/// Proof: `SmartContractModule::ActiveNodeContracts` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SmartContractModule::ActiveRentContractForNode` (r:1 w:0)
	/// Proof: `SmartContractModule::ActiveRentContractForNode` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TfgridModule::NodePower` (r:1 w:1)
	/// Proof: `TfgridModule::NodePower` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn change_power_target() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `792`
		//  Estimated: `4257`
		// Minimum execution time: 48_708_000 picoseconds.
		Weight::from_parts(54_009_000, 4257)
			.saturating_add(T::DbWeight::get().reads(6_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `TfgridModule::Twins` (r:1 w:0)
	/// Proof: `TfgridModule::Twins` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TfgridModule::TwinBoundedAccountID` (r:0 w:1)
	/// Proof: `TfgridModule::TwinBoundedAccountID` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn bond_twin_account() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `387`
		//  Estimated: `3852`
		// Minimum execution time: 23_881_000 picoseconds.
		Weight::from_parts(34_457_000, 3852)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `TfgridModule::TwinIdByAccountID` (r:1 w:0)
	/// Proof: `TfgridModule::TwinIdByAccountID` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TfgridModule::NodeIdByTwinID` (r:1 w:0)
	/// Proof: `TfgridModule::NodeIdByTwinID` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TfgridModule::Nodes` (r:1 w:0)
	/// Proof: `TfgridModule::Nodes` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	fn report_uptime_v2() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `454`
		//  Estimated: `3919`
		// Minimum execution time: 35_789_000 picoseconds.
		Weight::from_parts(48_751_000, 3919)
			.saturating_add(T::DbWeight::get().reads(4_u64))
	}
	/// Storage: `TfgridModule::TwinIdByAccountID` (r:1 w:0)
	/// Proof: `TfgridModule::TwinIdByAccountID` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TfgridModule::Nodes` (r:1 w:0)
	/// Proof: `TfgridModule::Nodes` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TfgridModule::Farms` (r:1 w:0)
	/// Proof: `TfgridModule::Farms` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TfgridModule::NodeV3BillingOptOut` (r:1 w:1)
	/// Proof: `TfgridModule::NodeV3BillingOptOut` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	fn opt_out_of_v3_billing() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `669`
		//  Estimated: `4134`
		// Minimum execution time: 41_988_000 picoseconds.
		Weight::from_parts(66_064_000, 4134)
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `TfgridModule::TwinIdByAccountID` (r:1 w:0)
	/// Proof: `TfgridModule::TwinIdByAccountID` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TfgridModule::Nodes` (r:1 w:0)
	/// Proof: `TfgridModule::Nodes` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TfgridModule::Farms` (r:1 w:0)
	/// Proof: `TfgridModule::Farms` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TfgridModule::NodeV3BillingOptOut` (r:1 w:0)
	/// Proof: `TfgridModule::NodeV3BillingOptOut` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TfgridModule::NodeV3OptOutMetadata` (r:0 w:1)
	/// Proof: `TfgridModule::NodeV3OptOutMetadata` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn set_node_v3_opt_out_metadata() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `712`
		//  Estimated: `4177`
		// Minimum execution time: 42_266_000 picoseconds.
		Weight::from_parts(45_201_000, 4177)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `TfgridModule::AllowedTwinAdmins` (r:1 w:1)
	/// Proof: `TfgridModule::AllowedTwinAdmins` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// The range of component `n` is `[0, 99]`.
	fn add_twin_admin(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `158 + n * (32 ±0)`
		//  Estimated: `1641 + n * (32 ±0)`
		// Minimum execution time: 15_747_000 picoseconds.
		Weight::from_parts(27_755_840, 1641)
			// Standard Error: 10_090
			.saturating_add(Weight::from_parts(85_801, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
			.saturating_add(Weight::from_parts(0, 32).saturating_mul(n.into()))
	}
	/// Storage: `TfgridModule::AllowedTwinAdmins` (r:1 w:1)
	/// Proof: `TfgridModule::AllowedTwinAdmins` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// The range of component `n` is `[1, 100]`.
	fn remove_twin_admin(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `158 + n * (32 ±0)`
		//  Estimated: `1643 + n * (32 ±0)`
		// Minimum execution time: 19_935_000 picoseconds.
		Weight::from_parts(33_349_529, 1643)
			// Standard Error: 8_880
			.saturating_add(Weight::from_parts(6_737, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
			.saturating_add(Weight::from_parts(0, 32).saturating_mul(n.into()))
	}
}

// For backwards compatibility and tests
impl WeightInfo for () {
	/// Storage: `TfgridModule::PalletVersion` (r:0 w:1)
	/// Proof: `TfgridModule::PalletVersion` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn set_storage_version() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 7_786_000 picoseconds.
		Weight::from_parts(8_665_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `TfgridModule::TwinIdByAccountID` (r:1 w:0)
	/// Proof: `TfgridModule::TwinIdByAccountID` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TfgridModule::Twins` (r:1 w:0)
	/// Proof: `TfgridModule::Twins` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TfgridModule::FarmIdByName` (r:1 w:1)
	/// Proof: `TfgridModule::FarmIdByName` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TfgridModule::FarmID` (r:1 w:1)
	/// Proof: `TfgridModule::FarmID` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `TfgridModule::Farms` (r:0 w:1)
	/// Proof: `TfgridModule::Farms` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn create_farm() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `496`
		//  Estimated: `3961`
		// Minimum execution time: 38_369_000 picoseconds.
		Weight::from_parts(54_973_000, 3961)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `TfgridModule::TwinIdByAccountID` (r:1 w:0)
	/// Proof: `TfgridModule::TwinIdByAccountID` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TfgridModule::Farms` (r:1 w:1)
	/// Proof: `TfgridModule::Farms` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TfgridModule::FarmIdByName` (r:1 w:2)
	/// Proof: `TfgridModule::FarmIdByName` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn update_farm() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `507`
		//  Estimated: `3972`
		// Minimum execution time: 59_376_000 picoseconds.
		Weight::from_parts(60_402_000, 3972)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `TfgridModule::TwinIdByAccountID` (r:1 w:0)
	/// Proof: `TfgridModule::TwinIdByAccountID` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TfgridModule::Farms` (r:1 w:0)
	/// Proof: `TfgridModule::Farms` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TfgridModule::FarmPayoutV2AddressByFarmID` (r:0 w:1)
	/// Proof: `TfgridModule::FarmPayoutV2AddressByFarmID` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn add_stellar_payout_v2address() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `453`
		//  Estimated: `3918`
		// Minimum execution time: 29_793_000 picoseconds.
		Weight::from_parts(30_517_000, 3918)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `TfgridModule::Farms` (r:1 w:1)
	/// Proof: `TfgridModule::Farms` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn set_farm_certification() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `412`
		//  Estimated: `3877`
		// Minimum execution time: 24_881_000 picoseconds.
		Weight::from_parts(25_611_000, 3877)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `TfgridModule::Farms` (r:1 w:1)
	/// Proof: `TfgridModule::Farms` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TfgridModule::Twins` (r:1 w:0)
	/// Proof: `TfgridModule::Twins` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn add_farm_ip() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `569`
		//  Estimated: `4034`
		// Minimum execution time: 33_632_000 picoseconds.
		Weight::from_parts(46_239_000, 4034)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `TfgridModule::Farms` (r:1 w:1)
	/// Proof: `TfgridModule::Farms` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TfgridModule::Twins` (r:1 w:0)
	/// Proof: `TfgridModule::Twins` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn remove_farm_ip() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `569`
		//  Estimated: `4034`
		// Minimum execution time: 32_071_000 picoseconds.
		Weight::from_parts(48_623_000, 4034)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `TfgridModule::Farms` (r:1 w:0)
	/// Proof: `TfgridModule::Farms` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TfgridModule::TwinIdByAccountID` (r:1 w:0)
	/// Proof: `TfgridModule::TwinIdByAccountID` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TfgridModule::NodeIdByTwinID` (r:1 w:1)
	/// Proof: `TfgridModule::NodeIdByTwinID` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TfgridModule::NodeID` (r:1 w:1)
	/// Proof: `TfgridModule::NodeID` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `TfgridModule::ConnectionPrice` (r:1 w:0)
	/// Proof: `TfgridModule::ConnectionPrice` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `TfgridModule::FarmingPoliciesMap` (r:4 w:0)
	/// Proof: `TfgridModule::FarmingPoliciesMap` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TfgridModule::NodesByFarmID` (r:1 w:1)
	/// Proof: `TfgridModule::NodesByFarmID` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Dao::FarmWeight` (r:1 w:1)
	/// Proof: `Dao::FarmWeight` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TfgridModule::Nodes` (r:0 w:1)
	/// Proof: `TfgridModule::Nodes` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn create_node() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `905`
		//  Estimated: `11795`
		// Minimum execution time: 90_616_000 picoseconds.
		Weight::from_parts(135_619_000, 11795)
			.saturating_add(RocksDbWeight::get().reads(12_u64))
			.saturating_add(RocksDbWeight::get().writes(5_u64))
	}
	/// Storage: `TfgridModule::Nodes` (r:1 w:1)
	/// Proof: `TfgridModule::Nodes` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TfgridModule::TwinIdByAccountID` (r:1 w:0)
	/// Proof: `TfgridModule::TwinIdByAccountID` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TfgridModule::Farms` (r:1 w:0)
	/// Proof: `TfgridModule::Farms` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Dao::FarmWeight` (r:1 w:1)
	/// Proof: `Dao::FarmWeight` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn update_node() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `661`
		//  Estimated: `4126`
		// Minimum execution time: 49_993_000 picoseconds.
		Weight::from_parts(51_155_000, 4126)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `TfgridModule::Nodes` (r:1 w:1)
	/// Proof: `TfgridModule::Nodes` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TfgridModule::FarmingPoliciesMap` (r:4 w:0)
	/// Proof: `TfgridModule::FarmingPoliciesMap` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TfgridModule::Farms` (r:1 w:0)
	/// Proof: `TfgridModule::Farms` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn set_node_certification() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `956`
		//  Estimated: `11846`
		// Minimum execution time: 64_630_000 picoseconds.
		Weight::from_parts(65_771_000, 11846)
			.saturating_add(RocksDbWeight::get().reads(6_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `TfgridModule::TwinIdByAccountID` (r:1 w:0)
	/// Proof: `TfgridModule::TwinIdByAccountID` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TfgridModule::NodeIdByTwinID` (r:1 w:0)
	/// Proof: `TfgridModule::NodeIdByTwinID` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TfgridModule::Nodes` (r:1 w:0)
	/// Proof: `TfgridModule::Nodes` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn report_uptime() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `454`
		//  Estimated: `3919`
		// Minimum execution time: 34_209_000 picoseconds.
		Weight::from_parts(35_067_000, 3919)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
	}
	/// Storage: `TfgridModule::Farms` (r:1 w:0)
	/// Proof: `TfgridModule::Farms` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TfgridModule::Twins` (r:1 w:0)
	/// Proof: `TfgridModule::Twins` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TfgridModule::Nodes` (r:1 w:1)
	/// Proof: `TfgridModule::Nodes` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn add_node_public_config() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `779`
		//  Estimated: `4244`
		// Minimum execution time: 45_290_000 picoseconds.
		Weight::from_parts(46_244_000, 4244)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `TfgridModule::Nodes` (r:1 w:1)
	/// Proof: `TfgridModule::Nodes` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TfgridModule::TwinIdByAccountID` (r:1 w:0)
	/// Proof: `TfgridModule::TwinIdByAccountID` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TfgridModule::NodesByFarmID` (r:1 w:1)
	/// Proof: `TfgridModule::NodesByFarmID` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SmartContractModule::ActiveNodeContracts` (r:1 w:0)
	/// Proof: `SmartContractModule::ActiveNodeContracts` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SmartContractModule::ActiveRentContractForNode` (r:1 w:0)
	/// Proof: `SmartContractModule::ActiveRentContractForNode` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Dao::FarmWeight` (r:1 w:1)
	/// Proof: `Dao::FarmWeight` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TfgridModule::NodeV3BillingOptOut` (r:0 w:1)
	/// Proof: `TfgridModule::NodeV3BillingOptOut` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn delete_node() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `682`
		//  Estimated: `4147`
		// Minimum execution time: 53_319_000 picoseconds.
		Weight::from_parts(77_405_000, 4147)
			.saturating_add(RocksDbWeight::get().reads(6_u64))
			.saturating_add(RocksDbWeight::get().writes(4_u64))
	}
	/// Storage: `TfgridModule::UsersTermsAndConditions` (r:1 w:0)
	/// Proof: `TfgridModule::UsersTermsAndConditions` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TfgridModule::TwinIdByAccountID` (r:1 w:1)
	/// Proof: `TfgridModule::TwinIdByAccountID` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TfgridModule::TwinID` (r:1 w:1)
	/// Proof: `TfgridModule::TwinID` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `TfgridModule::Twins` (r:0 w:1)
	/// Proof: `TfgridModule::Twins` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn create_twin() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `235`
		//  Estimated: `3700`
		// Minimum execution time: 27_879_000 picoseconds.
		Weight::from_parts(28_497_000, 3700)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `TfgridModule::TwinIdByAccountID` (r:1 w:0)
	/// Proof: `TfgridModule::TwinIdByAccountID` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TfgridModule::Twins` (r:1 w:1)
	/// Proof: `TfgridModule::Twins` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn update_twin() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `428`
		//  Estimated: `3893`
		// Minimum execution time: 28_399_000 picoseconds.
		Weight::from_parts(29_229_000, 3893)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `TfgridModule::PricingPolicyIdByName` (r:1 w:1)
	/// Proof: `TfgridModule::PricingPolicyIdByName` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TfgridModule::PricingPolicyID` (r:1 w:1)
	/// Proof: `TfgridModule::PricingPolicyID` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `TfgridModule::PricingPolicies` (r:0 w:1)
	/// Proof: `TfgridModule::PricingPolicies` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn create_pricing_policy() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `134`
		//  Estimated: `3599`
		// Minimum execution time: 23_679_000 picoseconds.
		Weight::from_parts(24_511_000, 3599)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `TfgridModule::PricingPolicies` (r:1 w:1)
	/// Proof: `TfgridModule::PricingPolicies` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TfgridModule::PricingPolicyIdByName` (r:1 w:1)
	/// Proof: `TfgridModule::PricingPolicyIdByName` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TfgridModule::PricingPolicyID` (r:0 w:1)
	/// Proof: `TfgridModule::PricingPolicyID` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn update_pricing_policy() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `382`
		//  Estimated: `3847`
		// Minimum execution time: 31_336_000 picoseconds.
		Weight::from_parts(33_796_000, 3847)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `TfgridModule::FarmingPolicyID` (r:1 w:1)
	/// Proof: `TfgridModule::FarmingPolicyID` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `TfgridModule::FarmingPoliciesMap` (r:0 w:1)
	/// Proof: `TfgridModule::FarmingPoliciesMap` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn create_farming_policy() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `134`
		//  Estimated: `1619`
		// Minimum execution time: 19_812_000 picoseconds.
		Weight::from_parts(20_457_000, 1619)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `TfgridModule::UsersTermsAndConditions` (r:1 w:1)
	/// Proof: `TfgridModule::UsersTermsAndConditions` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn user_accept_tc() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `140`
		//  Estimated: `3605`
		// Minimum execution time: 14_177_000 picoseconds.
		Weight::from_parts(14_759_000, 3605)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `TfgridModule::TwinIdByAccountID` (r:2 w:0)
	/// Proof: `TfgridModule::TwinIdByAccountID` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TfgridModule::Twins` (r:1 w:0)
	/// Proof: `TfgridModule::Twins` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TfgridModule::UsersTermsAndConditions` (r:1 w:0)
	/// Proof: `TfgridModule::UsersTermsAndConditions` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TfgridModule::PendingTransferByTwin` (r:1 w:1)
	/// Proof: `TfgridModule::PendingTransferByTwin` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TfgridModule::TwinTransferRequestID` (r:1 w:1)
	/// Proof: `TfgridModule::TwinTransferRequestID` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `TfgridModule::TwinTransferRequests` (r:0 w:1)
	/// Proof: `TfgridModule::TwinTransferRequests` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn request_twin_transfer() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `527`
		//  Estimated: `6467`
		// Minimum execution time: 44_601_000 picoseconds.
		Weight::from_parts(45_304_000, 6467)
			.saturating_add(RocksDbWeight::get().reads(6_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `TfgridModule::TwinTransferRequests` (r:1 w:1)
	/// Proof: `TfgridModule::TwinTransferRequests` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TfgridModule::Twins` (r:1 w:1)
	/// Proof: `TfgridModule::Twins` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TfgridModule::TwinIdByAccountID` (r:1 w:2)
	/// Proof: `TfgridModule::TwinIdByAccountID` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TfgridModule::PendingTransferByTwin` (r:0 w:1)
	/// Proof: `TfgridModule::PendingTransferByTwin` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn accept_twin_transfer() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `605`
		//  Estimated: `4070`
		// Minimum execution time: 50_032_000 picoseconds.
		Weight::from_parts(51_023_000, 4070)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(5_u64))
	}
	/// Storage: `TfgridModule::TwinTransferRequests` (r:1 w:1)
	/// Proof: `TfgridModule::TwinTransferRequests` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TfgridModule::PendingTransferByTwin` (r:0 w:1)
	/// Proof: `TfgridModule::PendingTransferByTwin` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn cancel_twin_transfer() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `403`
		//  Estimated: `3868`
		// Minimum execution time: 25_233_000 picoseconds.
		Weight::from_parts(26_372_000, 3868)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `TfgridModule::TwinIdByAccountID` (r:1 w:0)
	/// Proof: `TfgridModule::TwinIdByAccountID` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TfgridModule::Nodes` (r:1 w:1)
	/// Proof: `TfgridModule::Nodes` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TfgridModule::Farms` (r:1 w:0)
	/// Proof: `TfgridModule::Farms` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TfgridModule::NodesByFarmID` (r:1 w:1)
	/// Proof: `TfgridModule::NodesByFarmID` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SmartContractModule::ActiveNodeContracts` (r:1 w:0)
	/// Proof: `SmartContractModule::ActiveNodeContracts` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SmartContractModule::ActiveRentContractForNode` (r:1 w:0)
	/// Proof: `SmartContractModule::ActiveRentContractForNode` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Dao::FarmWeight` (r:1 w:1)
	/// Proof: `Dao::FarmWeight` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TfgridModule::NodeIdByTwinID` (r:0 w:1)
	/// Proof: `TfgridModule::NodeIdByTwinID` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn delete_node_farm() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `828`
		//  Estimated: `4293`
		// Minimum execution time: 62_557_000 picoseconds.
		Weight::from_parts(94_567_000, 4293)
			.saturating_add(RocksDbWeight::get().reads(7_u64))
			.saturating_add(RocksDbWeight::get().writes(4_u64))
	}
	/// Storage: `TfgridModule::Farms` (r:1 w:1)
	/// Proof: `TfgridModule::Farms` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn set_farm_dedicated() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `412`
		//  Estimated: `3877`
		// Minimum execution time: 36_903_000 picoseconds.
		Weight::from_parts(38_864_000, 3877)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `TfgridModule::Farms` (r:1 w:1)
	/// Proof: `TfgridModule::Farms` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn force_reset_farm_ip() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `412`
		//  Estimated: `3877`
		// Minimum execution time: 25_914_000 picoseconds.
		Weight::from_parts(27_545_000, 3877)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `TfgridModule::ConnectionPrice` (r:0 w:1)
	/// Proof: `TfgridModule::ConnectionPrice` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn set_connection_price() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 11_697_000 picoseconds.
		Weight::from_parts(18_668_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `TfgridModule::AllowedNodeCertifiers` (r:1 w:1)
	/// Proof: `TfgridModule::AllowedNodeCertifiers` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn add_node_certifier() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `355`
		//  Estimated: `1840`
		// Minimum execution time: 19_097_000 picoseconds.
		Weight::from_parts(30_428_000, 1840)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `TfgridModule::AllowedNodeCertifiers` (r:1 w:1)
	/// Proof: `TfgridModule::AllowedNodeCertifiers` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn remove_node_certifier() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `413`
		//  Estimated: `1898`
		// Minimum execution time: 28_443_000 picoseconds.
		Weight::from_parts(39_335_000, 1898)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `TfgridModule::FarmingPoliciesMap` (r:1 w:1)
	/// Proof: `TfgridModule::FarmingPoliciesMap` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn update_farming_policy() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `294`
		//  Estimated: `3759`
		// Minimum execution time: 25_275_000 picoseconds.
		Weight::from_parts(25_914_000, 3759)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `TfgridModule::FarmingPoliciesMap` (r:1 w:0)
	/// Proof: `TfgridModule::FarmingPoliciesMap` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TfgridModule::Farms` (r:1 w:1)
	/// Proof: `TfgridModule::Farms` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TfgridModule::NodesByFarmID` (r:1 w:0)
	/// Proof: `TfgridModule::NodesByFarmID` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn attach_policy_to_farm() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `572`
		//  Estimated: `4037`
		// Minimum execution time: 42_039_000 picoseconds.
		Weight::from_parts(42_748_000, 4037)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `TfgridModule::ZosVersion` (r:1 w:1)
	/// Proof: `TfgridModule::ZosVersion` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn set_zos_version() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `134`
		//  Estimated: `1619`
		// Minimum execution time: 15_354_000 picoseconds.
		Weight::from_parts(16_232_000, 1619)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `TfgridModule::TwinIdByAccountID` (r:1 w:0)
	/// Proof: `TfgridModule::TwinIdByAccountID` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TfgridModule::NodeIdByTwinID` (r:1 w:0)
	/// Proof: `TfgridModule::NodeIdByTwinID` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TfgridModule::Nodes` (r:1 w:0)
	/// Proof: `TfgridModule::Nodes` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TfgridModule::NodePower` (r:1 w:1)
	/// Proof: `TfgridModule::NodePower` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn change_power_state() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `621`
		//  Estimated: `4086`
		// Minimum execution time: 41_685_000 picoseconds.
		Weight::from_parts(43_574_000, 4086)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `TfgridModule::TwinIdByAccountID` (r:1 w:0)
	/// Proof: `TfgridModule::TwinIdByAccountID` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TfgridModule::Nodes` (r:1 w:0)
	/// Proof: `TfgridModule::Nodes` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TfgridModule::Farms` (r:1 w:0)
	/// Proof: `TfgridModule::Farms` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SmartContractModule::ActiveNodeContracts` (r:1 w:0)
	/// Proof: `SmartContractModule::ActiveNodeContracts` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SmartContractModule::ActiveRentContractForNode` (r:1 w:0)
	/// Proof: `SmartContractModule::ActiveRentContractForNode` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TfgridModule::NodePower` (r:1 w:1)
	/// Proof: `TfgridModule::NodePower` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn change_power_target() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `792`
		//  Estimated: `4257`
		// Minimum execution time: 48_708_000 picoseconds.
		Weight::from_parts(54_009_000, 4257)
			.saturating_add(RocksDbWeight::get().reads(6_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `TfgridModule::Twins` (r:1 w:0)
	/// Proof: `TfgridModule::Twins` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TfgridModule::TwinBoundedAccountID` (r:0 w:1)
	/// Proof: `TfgridModule::TwinBoundedAccountID` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn bond_twin_account() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `387`
		//  Estimated: `3852`
		// Minimum execution time: 23_881_000 picoseconds.
		Weight::from_parts(34_457_000, 3852)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `TfgridModule::TwinIdByAccountID` (r:1 w:0)
	/// Proof: `TfgridModule::TwinIdByAccountID` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TfgridModule::NodeIdByTwinID` (r:1 w:0)
	/// Proof: `TfgridModule::NodeIdByTwinID` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TfgridModule::Nodes` (r:1 w:0)
	/// Proof: `TfgridModule::Nodes` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	fn report_uptime_v2() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `454`
		//  Estimated: `3919`
		// Minimum execution time: 35_789_000 picoseconds.
		Weight::from_parts(48_751_000, 3919)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
	}
	/// Storage: `TfgridModule::TwinIdByAccountID` (r:1 w:0)
	/// Proof: `TfgridModule::TwinIdByAccountID` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TfgridModule::Nodes` (r:1 w:0)
	/// Proof: `TfgridModule::Nodes` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TfgridModule::Farms` (r:1 w:0)
	/// Proof: `TfgridModule::Farms` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TfgridModule::NodeV3BillingOptOut` (r:1 w:1)
	/// Proof: `TfgridModule::NodeV3BillingOptOut` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	fn opt_out_of_v3_billing() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `669`
		//  Estimated: `4134`
		// Minimum execution time: 41_988_000 picoseconds.
		Weight::from_parts(66_064_000, 4134)
			.saturating_add(RocksDbWeight::get().reads(5_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `TfgridModule::TwinIdByAccountID` (r:1 w:0)
	/// Proof: `TfgridModule::TwinIdByAccountID` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TfgridModule::Nodes` (r:1 w:0)
	/// Proof: `TfgridModule::Nodes` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TfgridModule::Farms` (r:1 w:0)
	/// Proof: `TfgridModule::Farms` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TfgridModule::NodeV3BillingOptOut` (r:1 w:0)
	/// Proof: `TfgridModule::NodeV3BillingOptOut` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TfgridModule::NodeV3OptOutMetadata` (r:0 w:1)
	/// Proof: `TfgridModule::NodeV3OptOutMetadata` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn set_node_v3_opt_out_metadata() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `712`
		//  Estimated: `4177`
		// Minimum execution time: 42_266_000 picoseconds.
		Weight::from_parts(45_201_000, 4177)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `TfgridModule::AllowedTwinAdmins` (r:1 w:1)
	/// Proof: `TfgridModule::AllowedTwinAdmins` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// The range of component `n` is `[0, 99]`.
	fn add_twin_admin(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `158 + n * (32 ±0)`
		//  Estimated: `1641 + n * (32 ±0)`
		// Minimum execution time: 15_747_000 picoseconds.
		Weight::from_parts(27_755_840, 1641)
			// Standard Error: 10_090
			.saturating_add(Weight::from_parts(85_801, 0).saturating_mul(n.into()))
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
			.saturating_add(Weight::from_parts(0, 32).saturating_mul(n.into()))
	}
	/// Storage: `TfgridModule::AllowedTwinAdmins` (r:1 w:1)
	/// Proof: `TfgridModule::AllowedTwinAdmins` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// The range of component `n` is `[1, 100]`.
	fn remove_twin_admin(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `158 + n * (32 ±0)`
		//  Estimated: `1643 + n * (32 ±0)`
		// Minimum execution time: 19_935_000 picoseconds.
		Weight::from_parts(33_349_529, 1643)
			// Standard Error: 8_880
			.saturating_add(Weight::from_parts(6_737, 0).saturating_mul(n.into()))
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
			.saturating_add(Weight::from_parts(0, 32).saturating_mul(n.into()))
	}
}
